### ISSUE TITLE
select option creatable 动态添加选项，添加后画面崩溃

### ISSUE THREAD

**Issue by wuyezhong** [baidu/amis#1403]
1. 你是如何使用 amis 的？
npm 1.1.1

2. 粘贴有问题的完整 `amis schema` 代码：
```
{
    "type": "dialog",
    "title": "新增权限",
    "body": [
        {
            "type": "form",
            "title": "表单",
            "controls": [
                {
                    "type": "text",
                    "label": "模块",
                    "name": "module",
                    "options": [
                    ],
                    "validations": {
                        "notEmptyString": ""
                    },
                    "creatable": true,
                    "required": true
                },
                {
                    "label": "功能",
                    "type": "text",
                    "name": "function",
                    "validations": {
                        "isAlphanumeric": true,
                        "notEmptyString": ""
                    },
                    "validationErrors": {
                    },
                    "required": true
                }
            ],
            "canAccessSuperData": false,
        }
    ],
    "closeOnEsc": false,
    "showCloseButton": true
}
```

3. 操作步骤
在一个crue画面中，顶部工具栏配置了一个添加按钮，类型为弹框，弹框中有个表单，表单中的第一个控件是select，配置了动态加载option和前端添加option，在点击添加option的弹框弹出后，点击取消或者输入option值点击确定，画面崩溃。

```
Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type: 'FormItemStore', Path upon death: '', Subpath: 'id', Action: '.removeSubFormItem()'). Either detach nodes first, or don't use objects after removing / replacing them in the tree.


    at Control (http://localhost:8000/vendors~p__org__Center~p__org__Organ~p__org__School~p__sys__Dict~p__sys__Notice~p__sys__Setting~p__u~74f40442.js:30549:38)
    at WithRootStore(Control) (http://localhost:8000/vendors~p__org__Center~p__org__Organ~p__org__School~p__sys__Dict~p__sys__Notice~p__sys__Setting~p__u~74f40442.js:16986:40)
    at Renderer (http://localhost:8000/vendors~p__org__Center~p__org__Organ~p__org__School~p__sys__Dict~p__sys__Notice~p__sys__Setting~p__u~74f40442.js:16375:24)
    at div
    at FormRenderer (http://localhost:8000/vendors~p__org__Center~p__org__Organ~p__org__School~p__sys__Dict~p__sys__Notice~p__sys__Setting~p__u~74f40442.js:44276:38)
    at WithStore(FormRenderer) (http://localhost:8000/vendors~p__org__Center~p__org__Organ~p__org__School~p__sys__Dict~p__sys__Notice~p__sys__Setting~p__u~74f40442.js:16587:42)
    at Scoped(WithStore(FormRenderer)) (http://localhost:8000/vendors~p__org__Center~p__org__Organ~p__org__School~p__sys__Dict~p__sys__Notice~p__sys__Setting~p__u~74f40442.js:476:45)
    at Renderer (http://localhost:8000/vendors~p__org__Center~p__org__Organ~p__org__School~p__sys__Dict~p__sys__Notice~p__sys__Setting~p__u~74f40442.js:16375:24)
    at div
    at div
```

奇怪的是我在amis-editor中配置后预览，并没有这个问题。
目前我先用text控件配置option前端添加了，这个没问题，用select就会有问题。

**Comment by wuyezhong** [comment]
升级到`1.1.2-beta.2`，没问题了
