### ISSUE TITLE
api请求时，name如果为xx.xx，会自动转换成xx[xx]，引发非法字符异常。

### ISSUE THREAD

**Issue by tonglsh** [baidu/amis#2323]
#### 描述问题：
api请求时，name如果为xx.xx，会自动转换成xx[xx]，引发非法字符异常。

#### 截图或视频：

![image](https://user-images.githubusercontent.com/57531513/126956570-e3d4e30d-77e9-4734-a8aa-2de6938b7dd2.png)

后端异常

```
java.lang.IllegalArgumentException: Invalid character found in the request target [/apiv2/systemEventLog?class[number]=12098 ]. The valid characters are defined in RFC 7230 and RFC 3986
	at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:494) ~[tomcat-embed-core-9.0.50.jar:9.0.50]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:269) ~[tomcat-embed-core-9.0.50.jar:9.0.50]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.50.jar:9.0.50]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893) ~[tomcat-embed-core-9.0.50.jar:9.0.50]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1723) ~[tomcat-embed-core-9.0.50.jar:9.0.50]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.50.jar:9.0.50]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.50.jar:9.0.50]
	at java.base/java.lang.Thread.run(Thread.java:831) ~[na:na]
```

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`npm` 

2. 粘贴有问题的完整 `amis schema` 代码：

复现很容易，api请求只要是请求参数是这种xx.xx 都会被转换成xx[xx]
```
      schema: {
        type: 'page',
        initApi: {
          url: 'apiv2/systemEventLog',
          method: 'get',
          data: {
            'class.number': '12098'
          }
        }
      }
```

**Comment by hetaochen** [comment]
https://github.com/baidu/amis/pull/1990/files

**Comment by Lijie0981** [comment]
**描述问题：** post请求也有相同的问题
**如何复现（请务必完整填写下面内容）：** 同上
```
{
    "type": "page",
    "body": [
        {
            "type": "form",
            "api": {
                "method": "post",
                "url": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
                "data": {
                    "myName": "${name}",
                    "myEmail.123": "${email}"
                }
            },
            "body": [
                {
                    "type": "input-text",
                    "name": "name",
                    "label": "姓名："
                },
                {
                    "name": "email",
                    "type": "input-email",
                    "label": "邮箱："
                }
            ]
        }
    ],
    "title": "123",
    "subTitle": "asd",
    "remark": "asd"
}
```
**截图或视频：**
![image](https://user-images.githubusercontent.com/17643561/129704418-81c751ee-bd6e-4201-b72a-19c26fd031fe.png)

**Comment by Lijie0981** [comment]
@2betop 大佬，能看看不。现在我不太清楚这个问题的性质是feature or bug。

**Comment by 2betop** [comment]
目前这个是故意的且管不了，后续可以考虑来个开关

**Comment by nwind** [comment]
#2870
