### ISSUE TITLE
简单使用报错Uncaught TypeError: i.__spreadArray is not a function

### ISSUE THREAD

**Issue by lucasyue** [baidu/amis#4020]
请帮看下哪里除了问题，谢谢。
版本：react17,npm i amis,npm i amis-editor
使用代码：
import {Editor} from 'amis-editor';

function App() {
  let pjson={};
  return (
    <Editor value={pjson}>
    </Editor>
  );
}
export default App;
页面报错：
Uncaught TypeError: i.__spreadArray is not a function
    at disabled (index.min.js:1:1)
    at h (index.min.js:1:1)
    at new t (index.min.js:1:1)
    at index.min.js:1:1
    at Array.map (<anonymous>)
    at new e (index.min.js:1:1)
    at new t (index.min.js:1:1)
    at constructClassInstance (react-dom.development.js:12708:1)
    at updateClassComponent (react-dom.development.js:17417:1)
    at beginWork (react-dom.development.js:19065:1)
react-dom.development.js:20077 The above error occurred in the <t> component:

    at t (http://localhost:3000/static/js/bundle.js:4055:21)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:20077
bootstrap:27 Uncaught TypeError: i.__spreadArray is not a function
    at disabled (index.min.js:1:1)
    at h (index.min.js:1:1)
    at new t (index.min.js:1:1)
    at index.min.js:1:1
    at Array.map (<anonymous>)
    at new e (index.min.js:1:1)
    at new t (index.min.js:1:1)
    at constructClassInstance (react-dom.development.js:12708:1)
    at updateClassComponent (react-dom.development.js:17417:1)
    at beginWork (react-dom.development.js:19065:1)

**Comment by lucasyue** [comment]
使用代码见下图：
![image](https://user-images.githubusercontent.com/5989099/162856551-2091e846-c5c8-416b-9524-c925fd124fea.png)

**Comment by lucasyue** [comment]
使用问题!
