### ISSUE TITLE
npm run dev 报错 node10.0.0

### ISSUE THREAD

**Issue by westeast** [baidu/amis#432]
[WARNI] SourceMap Merge Error: Cannot read property 'substr' of undefined
TypeError: Cannot read property 'substr' of undefined
    at Function.<anonymous> (/Users/likenan/git/easymis/amis/node_modules/fis3-hook-commonjs/node_modules/source-map/lib/source-node.js:121:27)
    at Array.forEach (<anonymous>)
    at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/Users/likenan/git/easymis/amis/node_modules/fis3-hook-commonjs/node_modules/source-map/lib/source-map-consumer.js:155:14)
    at Function.SourceNode_fromStringWithSourceMap [as fromStringWithSourceMap] (/Users/likenan/git/easymis/amis/node_modules/fis3-hook-commonjs/node_modules/source-map/lib/source-node.js:86:24)
    at module.exports (/Users/likenan/git/easymis/amis/node_modules/fis3-hook-commonjs/wrap.js:63:45)
    at EventEmitter.<anonymous> (/Users/likenan/git/easymis/amis/node_modules/fis3-hook-commonjs/index.js:16:5)
    at EventEmitter.emit (events.js:187:15)
    at Object.fis.(anonymous function) [as emit] (/Users/likenan/git/easymis/amis/node_modules/fis3/lib/fis.js:91:25)
    at pipe (/Users/likenan/git/easymis/amis/node_modules/fis3/lib/compile.js:642:7)
    at process (/Users/likenan/git/easymis/amis/node_modules/fis3/lib/compile.js:608:3)
.................................................................................................................................................................................................................
 [ERROR] parser.typescript: Syntax Error: Expression expected. in [199:42] [/Users/likenan/git/easymis/amis/src/renderers/Form/Combo.tsx]

**Comment by 2betop** [comment]
fis3-parser-typescript 版本低了，用最新版本。用了最新的 typescript 语法

**Comment by westeast** [comment]
> fis3-parser-typescript 版本低了，用最新版本。用了最新的 typescript 语法

多谢，删除node_modules 重新安装 ，error没了。
这个warning有办法 解决吗？
[WARNI] SourceMap Merge Error: Cannot read property 'substr' of undefined
TypeError: Cannot read property 'substr' of undefined

**Comment by RickCole21** [comment]
这个应该不影响
