### ISSUE TITLE
Editor使用报错

### ISSUE THREAD

**Issue by tipsxBase** [baidu/amis#4323]
页面(5a535bb99c86)渲染发生错误：
当前渲染器信息：
 {
   $schema: "/schemas/PageSchema.json"
   disabledRendererPlugin: undefined
   filterProps: undefined
   id: "5a535bb99c86"
    isBaseComponent: true
   multifactor: undefined
   name: "页面"
   patchContainers: undefined
   plugin:  {manager: e, rendererName: 'page', $schema: '/schemas/PageSchema.json', name: '页面', isBaseComponent: true, …}
   regions: (3) [{…}, {…}, {…}]
   renderRenderer: undefined
   renderer: {type: 'page', storeType: 'ServiceStore', isolateScope: true, test: /(^|\/)\/page\/i$/i, component: ƒ, …}
   rendererName:"page"
    scaffoldForm: undefined
    schemaPath: ""
    vRendererConfig: undefined
    wrapperProps: undefined
    wrapperResolve: undefined
错误对象： Error: [mobx-state-tree] You are trying to read or write to an object that is no longer part of a state tree. (Object type: 'EditorNode', Path upon death: '/root/children/0/children/0', Subpath: 'id', Action: ''). Either detach nodes first, or don't use objects after removing / replacing them in the tree.
    at fail$1 (mobx-state-tree.module.js:3128:1)
    at ObjectNode.assertAlive (mobx-state-tree.module.js:1508:1)
    at ObjectNode.unbox (mobx-state-tree.module.js:1580:1)
    at ObservableValue.dehanceValue (mobx.module.js:932:1)
    at ObservableValue.get (mobx.module.js:985:1)
    at ObservableObjectAdministration.read (mobx.module.js:1027:1)
    at Object.get [as id] (mobx.module.js:1212:1)
    at t.componentDidMount (index.min.js:1:1)
    at invokeLayoutEffectMountInDEV (react-dom.development.js:25023:1)
    at invokeEffectsInDev (react-dom.development.js:27304:1)

**Comment by tipsxBase** [comment]
我的代码

import { Layout, Switch, classnames as cx, toast, SchemaObject } from 'amis';
import 'amis-editor/dist/style.css';
import 'amis/lib/themes/default.css';
import 'amis/lib/themes/cxd.css';
import { Editor } from 'amis-editor';
import { useState } from 'react';

let host = `${window.location.protocol}//${window.location.host}`;

const schemaUrl = `${host}/schema.json`;

const AmisEditor = function (props: any) {
  const [schema, setSchema] = useState<SchemaObject>({
    body: '初始页面',
    title: 'Hello world',
    type: 'page',
  });

  function exit() {}

  function renderHeader() {
    return (
      <div className="editor-header clearfix box-shadow bg-dark">
        <div className="editor-preview">
          预览{' '}
          <Switch
            value={false}
            onChange={(value: boolean) => {}}
            className="m-l-xs"
            inline
          />
        </div>

        <div className="editor-preview">
          移动端{' '}
          <Switch
            value={false}
            onChange={(value: boolean) => {}}
            className="m-l-xs"
            inline
          />
        </div>

        <div className="editor-header-btns">
          <div className={cx('btn-item')} onClick={() => {}}>
            保存
          </div>

          <div className="btn-item" onClick={exit}>
            退出
          </div>
        </div>
      </div>
    );
  }

  return (
    <Layout header={renderHeader()} headerFixed={false}>
      <Editor
        preview={false}
        value={schema}
        onChange={setSchema}
        className="is-fixed"
      />
    </Layout>
  );
};

export default AmisEditor;

**Comment by tipsxBase** [comment]
我的代码
```
import { Layout, Switch, classnames as cx, toast, SchemaObject } from 'amis';
import 'amis-editor/dist/style.css';
import 'amis/lib/themes/default.css';
import 'amis/lib/themes/cxd.css';
import { Editor } from 'amis-editor';
import { useState } from 'react';

let host = `${window.location.protocol}//${window.location.host}`;

const schemaUrl = `${host}/schema.json`;

const AmisEditor = function (props: any) {
  const [schema, setSchema] = useState<SchemaObject>({
    body: '初始页面',
    title: 'Hello world',
    type: 'page',
  });

  function exit() {}

  function renderHeader() {
    return (
      <div className="editor-header clearfix box-shadow bg-dark">
        <div className="editor-preview">
          预览{' '}
          <Switch
            value={false}
            onChange={(value: boolean) => {}}
            className="m-l-xs"
            inline
          />
        </div>

        <div className="editor-preview">
          移动端{' '}
          <Switch
            value={false}
            onChange={(value: boolean) => {}}
            className="m-l-xs"
            inline
          />
        </div>

        <div className="editor-header-btns">
          <div className={cx('btn-item')} onClick={() => {}}>
            保存
          </div>

          <div className="btn-item" onClick={exit}>
            退出
          </div>
        </div>
      </div>
    );
  }

  return (
    <Layout header={renderHeader()} headerFixed={false}>
      <Editor
        preview={false}
        value={schema}
        onChange={setSchema}
        className="is-fixed"
      />
    </Layout>
  );
};

export default AmisEditor;

```

**Comment by tipsxBase** [comment]
![image](https://user-images.githubusercontent.com/16009561/168050410-c2087ddb-dac3-4ad2-b241-d855a4ab8496.png)

**Comment by tipsxBase** [comment]
![image](https://user-images.githubusercontent.com/16009561/168050652-ecc479ce-a32d-4c76-ac53-dc3cab62abde.png)

**Comment by wibetter** [comment]
用你提供的代码，在本地能正常跑起来。能说下你那边是做了什么操作后控制台才出现这种报错吗？

**Comment by fanzhenyang** [comment]
> 用你提供的代码，在本地能正常跑起来。能说下你那边是做了什么操作后控制台才出现这种报错吗？
Encountered an uncaught exception that was thrown by a reaction or observer component, in: 'Reaction[Reaction@103]' TypeError: t.onChange is not a function
我这边使用的时候，将它出拽到画布中，就立刻报错，但是我的amis-editor没有去依赖其他包呀
