### ISSUE TITLE
ERESOLVE unable to resolve dependency tree

### ISSUE THREAD

**Issue by wencan** [baidu/amis#4464]
$ uname -a
`Linux skynet 5.10.0-13-amd64 #1 SMP Debian 5.10.106-1 (2022-03-17) x86_64 GNU/Linux`

$ npm -version
`7.5.2`

$ npm i amis
```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   peer react@">=16.8.6" from amis@1.9.1-beta.17
npm ERR!   node_modules/amis
npm ERR!     amis@"*" from the root project
npm ERR!   peer react@"^18.1.0" from react-dom@18.1.0
npm ERR!   node_modules/react-dom
npm ERR!     peer react-dom@">=16.8.6" from amis@1.9.1-beta.17
npm ERR!     node_modules/amis
npm ERR!       amis@"*" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.3.2 || ^17.0.0" from ansi-to-react@6.1.6
npm ERR! node_modules/amis/node_modules/ansi-to-react
npm ERR!   ansi-to-react@"^6.1.6" from amis@1.9.1-beta.17
npm ERR!   node_modules/amis
npm ERR!     amis@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /home/User/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/User/.npm/_logs/2022-05-26T12_53_12_485Z-debug.log

```

$ cat /home/User/.npm/eresolve-report.txt
```
# npm resolution error report

2022-05-26T12:53:12.481Z

Found: react@18.1.0
node_modules/react
  peer react@">=16.8.6" from amis@1.9.1-beta.17
  node_modules/amis
    amis@"*" from the root project
  peer react@"^18.1.0" from react-dom@18.1.0
  node_modules/react-dom
    peer react-dom@">=16.8.6" from amis@1.9.1-beta.17
    node_modules/amis
      amis@"*" from the root project

Could not resolve dependency:
peer react@"^16.3.2 || ^17.0.0" from ansi-to-react@6.1.6
node_modules/amis/node_modules/ansi-to-react
  ansi-to-react@"^6.1.6" from amis@1.9.1-beta.17
  node_modules/amis
    amis@"*" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "react",
    "version": "18.1.0",
    "location": "node_modules/react",
    "dependents": [
      {
        "type": "peer",
        "name": "react",
        "spec": ">=16.8.6",
        "from": {
          "name": "amis",
          "version": "1.9.1-beta.17",
          "location": "node_modules/amis",
          "dependents": [
            {
              "type": "prod",
              "name": "amis",
              "spec": "*",
              "from": {
                "location": "/home/User"
              }
            }
          ]
        }
      },
      {
        "type": "peer",
        "name": "react",
        "spec": "^18.1.0",
        "from": {
          "name": "react-dom",
          "version": "18.1.0",
          "location": "node_modules/react-dom",
          "dependents": [
            {
              "type": "peer",
              "name": "react-dom",
              "spec": ">=16.8.6",
              "from": {
                "name": "amis",
                "version": "1.9.1-beta.17",
                "location": "node_modules/amis",
                "dependents": [
                  {
                    "type": "prod",
                    "name": "amis",
                    "spec": "*",
                    "from": {
                      "location": "/home/User"
                    }
                  }
                ]
              }
            }
          ]
        }
      }
    ]
  },
  "edge": {
    "type": "peer",
    "name": "react",
    "spec": "^16.3.2 || ^17.0.0",
    "error": "INVALID",
    "from": {
      "name": "ansi-to-react",
      "version": "6.1.6",
      "location": "node_modules/amis/node_modules/ansi-to-react",
      "dependents": [
        {
          "type": "prod",
          "name": "ansi-to-react",
          "spec": "^6.1.6",
          "from": {
            "name": "amis",
            "version": "1.9.1-beta.17",
            "location": "node_modules/amis",
            "dependents": [
              {
                "type": "prod",
                "name": "amis",
                "spec": "*",
                "from": {
                  "location": "/home/User"
                }
              }
            ]
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
}
```

$ cat /home/User/.npm/_logs/2022-05-26T12_53_12_485Z-debug.log
```
0 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'i', 'amis' ]
1 info using npm@7.5.2
2 info using node@v12.22.5
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/share/nodejs/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 0ms
8 timing config:load:project Completed in 1ms
9 timing config:load:file:/home/User/.npmrc Completed in 0ms
10 timing config:load:user Completed in 0ms
11 timing config:load:file:/etc/npmrc Completed in 0ms
12 timing config:load:global Completed in 0ms
13 timing config:load:cafile Completed in 0ms
14 timing config:load:validate Completed in 0ms
15 timing config:load:setUserAgent Completed in 1ms
16 timing config:load:setEnvs Completed in 0ms
17 timing config:load Completed in 7ms
18 verbose npm-session a0fabe75c0b3bcad
19 timing npm:load Completed in 15ms
20 timing arborist:ctor Completed in 1ms
21 timing idealTree:init Completed in 9ms
22 timing idealTree:userRequests Completed in 1ms
23 silly idealTree buildDeps
24 silly fetch manifest amis@*
25 http fetch GET 304 https://registry.npmjs.org/amis 1862ms (from cache)
26 silly fetch manifest react@>=16.8.6
27 http fetch GET 304 https://registry.npmjs.org/react 1624ms (from cache)
28 silly fetch manifest react-dom@>=16.8.6
29 http fetch GET 200 https://registry.npmjs.org/react-dom 6ms (from cache)
30 silly placeDep ROOT amis@1.9.1-beta.17 OK for:  want: *
31 silly placeDep ROOT react@18.1.0 OK for: amis@1.9.1-beta.17 want: >=16.8.6
32 silly placeDep ROOT react-dom@18.1.0 OK for: amis@1.9.1-beta.17 want: >=16.8.6
33 silly fetch manifest amis-formula@^1.3.15
34 silly fetch manifest ansi-to-react@^6.1.6
35 silly fetch manifest attr-accept@2.2.2
36 silly fetch manifest blueimp-canvastoblob@2.1.0
37 silly fetch manifest classnames@2.3.1
38 silly fetch manifest codemirror@^5.63.0
39 silly fetch manifest downshift@6.1.7
40 silly fetch manifest echarts@5.3.1
41 silly fetch manifest echarts-stat@^1.2.0
42 silly fetch manifest exceljs@^4.3.0
43 silly fetch manifest file-saver@^2.0.2
44 silly fetch manifest froala-editor@3.1.1
45 silly fetch manifest hls.js@1.1.3
46 silly fetch manifest hoist-non-react-statics@^3.3.2
47 silly fetch manifest hotkeys-js@^3.8.7
48 silly fetch manifest immutability-helper@^3.1.1
49 silly fetch manifest jsbarcode@^3.11.5
50 silly fetch manifest keycode@^2.2.1
51 silly fetch manifest lodash@^4.17.15
52 silly fetch manifest markdown-it@^12.0.6
53 silly fetch manifest markdown-it-html5-media@^0.7.1
54 silly fetch manifest match-sorter@^6.3.1
55 silly fetch manifest mobx@^4.5.0
56 silly fetch manifest mobx-react@^6.3.1
57 silly fetch manifest mobx-state-tree@^3.17.3
58 silly fetch manifest moment@^2.19.3
59 silly fetch manifest monaco-editor@0.30.1
60 silly fetch manifest mpegts.js@^1.6.10
61 silly fetch manifest papaparse@^5.3.0
62 silly fetch manifest prop-types@^15.6.1
63 silly fetch manifest punycode@^2.1.1
64 silly fetch manifest qrcode.react@^3.0.0
65 silly fetch manifest qs@6.9.7
66 silly fetch manifest rc-input-number@^7.3.4
67 silly fetch manifest rc-overflow@^1.2.4
68 silly fetch manifest rc-progress@^3.1.4
69 silly fetch manifest react-color@^2.19.3
70 silly fetch manifest react-cropper@^2.1.8
71 silly fetch manifest react-dropzone@^11.4.2
72 silly fetch manifest react-hook-form@7.30.0
73 silly fetch manifest react-input-range@1.3.0
74 silly fetch manifest react-json-view@1.21.3
75 silly fetch manifest react-overlays@5.1.1
76 silly fetch manifest react-textarea-autosize@8.3.3
77 silly fetch manifest react-transition-group@4.4.2
78 silly fetch manifest react-visibility-sensor@5.1.1
79 silly fetch manifest sortablejs@1.14.0
80 silly fetch manifest tinymce@^5.10.3
81 silly fetch manifest tslib@^2.3.1
82 silly fetch manifest uncontrollable@7.2.1
83 silly fetch manifest video-react@0.15.0
84 silly fetch manifest loose-envify@^1.1.0
85 silly fetch manifest scheduler@^0.22.0
86 http fetch GET 200 https://registry.npmjs.org/classnames 176ms (from cache)
87 http fetch GET 200 https://registry.npmjs.org/keycode 160ms (from cache)
88 http fetch GET 200 https://registry.npmjs.org/lodash 159ms (from cache)
89 http fetch GET 200 https://registry.npmjs.org/react-color 145ms (from cache)
90 http fetch GET 200 https://registry.npmjs.org/react-cropper 146ms (from cache)
91 http fetch GET 200 https://registry.npmjs.org/react-json-view 144ms (from cache)
92 http fetch GET 304 https://registry.npmjs.org/react-transition-group 2754ms (from cache)
93 http fetch GET 304 https://registry.npmjs.org/rc-overflow 2769ms (from cache)
94 http fetch GET 304 https://registry.npmjs.org/loose-envify 2963ms (from cache)
95 http fetch GET 304 https://registry.npmjs.org/file-saver 3007ms (from cache)
96 http fetch GET 304 https://registry.npmjs.org/prop-types 2988ms (from cache)
97 http fetch GET 304 https://registry.npmjs.org/react-textarea-autosize 2972ms (from cache)
98 http fetch GET 304 https://registry.npmjs.org/react-visibility-sensor 2972ms (from cache)
99 http fetch GET 304 https://registry.npmjs.org/downshift 3015ms (from cache)
100 http fetch GET 304 https://registry.npmjs.org/hotkeys-js 3012ms (from cache)
101 http fetch GET 304 https://registry.npmjs.org/papaparse 3005ms (from cache)
102 http fetch GET 304 https://registry.npmjs.org/tslib 2986ms (from cache)
103 http fetch GET 304 https://registry.npmjs.org/video-react 3015ms (from cache)
104 http fetch GET 304 https://registry.npmjs.org/echarts-stat 3075ms (from cache)
105 http fetch GET 304 https://registry.npmjs.org/tinymce 3069ms (from cache)
106 http fetch GET 304 https://registry.npmjs.org/punycode 3093ms (from cache)
107 http fetch GET 304 https://registry.npmjs.org/froala-editor 3118ms (from cache)
108 http fetch GET 304 https://registry.npmjs.org/scheduler 3088ms (from cache)
109 http fetch GET 304 https://registry.npmjs.org/rc-progress 3116ms (from cache)
110 http fetch GET 304 https://registry.npmjs.org/echarts 3144ms (from cache)
111 http fetch GET 304 https://registry.npmjs.org/attr-accept 3159ms (from cache)
112 http fetch GET 304 https://registry.npmjs.org/mobx-state-tree 3135ms (from cache)
113 http fetch GET 304 https://registry.npmjs.org/qs 3134ms (from cache)
114 http fetch GET 304 https://registry.npmjs.org/hoist-non-react-statics 3169ms (from cache)
115 http fetch GET 304 https://registry.npmjs.org/markdown-it 3168ms (from cache)
116 http fetch GET 304 https://registry.npmjs.org/rc-input-number 3164ms (from cache)
117 http fetch GET 304 https://registry.npmjs.org/moment 3181ms (from cache)
118 http fetch GET 304 https://registry.npmjs.org/match-sorter 3397ms (from cache)
119 http fetch GET 304 https://registry.npmjs.org/codemirror 3417ms (from cache)
120 http fetch GET 304 https://registry.npmjs.org/ansi-to-react 3422ms (from cache)
121 http fetch GET 304 https://registry.npmjs.org/sortablejs 3375ms (from cache)
122 http fetch GET 304 https://registry.npmjs.org/jsbarcode 3406ms (from cache)
123 http fetch GET 304 https://registry.npmjs.org/react-overlays 3385ms (from cache)
124 http fetch GET 304 https://registry.npmjs.org/mobx-react 3404ms (from cache)
125 http fetch GET 304 https://registry.npmjs.org/monaco-editor 3407ms (from cache)
126 http fetch GET 304 https://registry.npmjs.org/hls.js 3436ms (from cache)
127 http fetch GET 304 https://registry.npmjs.org/blueimp-canvastoblob 3480ms (from cache)
128 http fetch GET 304 https://registry.npmjs.org/react-input-range 3447ms (from cache)
129 http fetch GET 304 https://registry.npmjs.org/qrcode.react 3470ms (from cache)
130 http fetch GET 304 https://registry.npmjs.org/mpegts.js 3474ms (from cache)
131 http fetch GET 304 https://registry.npmjs.org/uncontrollable 3451ms (from cache)
132 http fetch GET 304 https://registry.npmjs.org/immutability-helper 3487ms (from cache)
133 http fetch GET 304 https://registry.npmjs.org/amis-formula 3507ms (from cache)
134 http fetch GET 304 https://registry.npmjs.org/mobx 3488ms (from cache)
135 http fetch GET 304 https://registry.npmjs.org/react-dropzone 3483ms (from cache)
136 http fetch GET 304 https://registry.npmjs.org/exceljs 3696ms (from cache)
137 http fetch GET 304 https://registry.npmjs.org/react-hook-form 3732ms (from cache)
138 http fetch GET 304 https://registry.npmjs.org/markdown-it-html5-media 4028ms (from cache)
139 timing idealTree:#root Completed in 7591ms
140 silly fetch manifest react@^16.3.2 || ^17.0.0
141 silly fetch manifest react-dom@^16.3.2 || ^17.0.0
142 silly fetch manifest react@^16.8.0 || 16.9.0-alpha.0
143 silly fetch manifest react@^15.0.0 || ^16.0.0
144 silly fetch manifest react-dom@^15.0.0 || ^16.0.0
145 silly fetch manifest react@^17.0.0 || ^16.3.0 || ^15.5.4
146 silly fetch manifest react-dom@^17.0.0 || ^16.3.0 || ^15.5.4
147 silly fetch manifest react@^16.8.0 || ^17.0.0
148 silly fetch manifest react@^15.0.0 || ^16.0.0 || ^17.0.0
149 silly fetch manifest react-dom@^15.0.0 || ^16.0.0 || ^17.0.0
150 silly placeDep ROOT amis-formula@1.3.15 OK for: amis@1.9.1-beta.17 want: ^1.3.15
151 silly placeDep node_modules/amis ansi-to-react@6.1.6 OK for: amis@1.9.1-beta.17 want: ^6.1.6
152 timing idealTree Completed in 7820ms
153 timing command:install Completed in 7839ms
154 verbose stack Error: unable to resolve dependency tree
154 verbose stack     at Arborist.[failPeerConflict] (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1115:25)
154 verbose stack     at Arborist.[placeDep] (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1201:30)
154 verbose stack     at Arborist.[placeDep] (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1339:41)
154 verbose stack     at /usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:835:46
154 verbose stack     at Array.map (<anonymous>)
154 verbose stack     at Arborist.[buildDepStep] (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:835:8)
154 verbose stack     at async Arborist.buildIdealTree (/usr/share/nodejs/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
154 verbose stack     at async Promise.all (index 1)
154 verbose stack     at async Arborist.reify (/usr/share/nodejs/@npmcli/arborist/lib/arborist/reify.js:127:5)
154 verbose stack     at async install (/usr/share/nodejs/npm/lib/install.js:38:3)
155 verbose cwd /home/User
156 verbose Linux 5.10.0-13-amd64
157 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "amis"
158 verbose node v12.22.5
159 verbose npm  v7.5.2
160 error code ERESOLVE
161 error ERESOLVE unable to resolve dependency tree
162 error
163 error Found: react@18.1.0
163 error node_modules/react
163 error   peer react@">=16.8.6" from amis@1.9.1-beta.17
163 error   node_modules/amis
163 error     amis@"*" from the root project
163 error   peer react@"^18.1.0" from react-dom@18.1.0
163 error   node_modules/react-dom
163 error     peer react-dom@">=16.8.6" from amis@1.9.1-beta.17
163 error     node_modules/amis
163 error       amis@"*" from the root project
163 error
163 error Could not resolve dependency:
163 error peer react@"^16.3.2 || ^17.0.0" from ansi-to-react@6.1.6
163 error node_modules/amis/node_modules/ansi-to-react
163 error   ansi-to-react@"^6.1.6" from amis@1.9.1-beta.17
163 error   node_modules/amis
163 error     amis@"*" from the root project
163 error
163 error Fix the upstream dependency conflict, or retry
163 error this command with --force, or --legacy-peer-deps
163 error to accept an incorrect (and potentially broken) dependency resolution.
163 error
163 error See /home/User/.npm/eresolve-report.txt for a full report.
164 verbose exit 1

```

**Comment by wencan** [comment]
换上node v18.2.0，npm 8.9.0 解决了
