### ISSUE TITLE
升级2.0.0 报remark已存在

### ISSUE THREAD

**Issue by yangyining** [baidu/amis#4777]
#### 描述问题：

```
bootstrap:27 
        
       Uncaught Error: The renderer with name "remark" has already exists, please try another name!
    at registerRenderer (factory.js:53:1)
    at factory.js:33:1
    at Module.__decorate (tslib.es6.js:58:54)
    at Remark.js:100:1
    at ./node_modules/.pnpm/amis@2.0.0_ne5ryh2ajzsrup2rhnpwv6ryca/node_modules/amis/lib/renderers/Remark.js (Remark.js:106:2)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)
    at ./node_modules/.pnpm/amis@2.0.0_ne5ryh2ajzsrup2rhnpwv6ryca/node_modules/amis/lib/renderers/Action.js (Action.js:17:14)
    at __webpack_require__ (bootstrap:24:1)
    at fn (hot module replacement:61:1)

```

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
npm

2. 2.0.0

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
大概是你有个自定义组件也叫 remark，换个名字

**Comment by dong-gy** [comment]
我也有这个问题，好像是这两个路径下都有个Remark.js的组件，名字一样
![image](https://user-images.githubusercontent.com/48462501/178914334-78d56952-33d8-463c-a856-3165b447c7f5.png)

**Comment by 0undefined0** [comment]
同样的问题

**Comment by jokingzhang** [comment]
同样的问题

**Comment by henrycc2015** [comment]
同样的问题

**Comment by ggymzz** [comment]
同样的问题

**Comment by ChLiaoXiang** [comment]
同样的问题

**Comment by shuracwf** [comment]
> 大概是你有个自定义组件也叫 remark，换个名字

没有remark的自定义组件，升级到amis^2.6.0一样报这个错误，还没解决么？

**Comment by seantech2000** [comment]
无解

**Comment by seantech2000** [comment]
> 

无解
