### ISSUE TITLE
crud的list模式内嵌cards报错TypeError: t.indexOf is not a function

### ISSUE THREAD

**Issue by zljun2010** [baidu/amis#4902]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...

#### 截图或视频：

报错：
```
TypeError: t.indexOf is not a function

    at t (http://127.0.0.1:5500/sdk/sdk.js:3284:13503)
    at r (http://127.0.0.1:5500/sdk/sdk.js:2178:486)
    at t (http://127.0.0.1:5500/sdk/sdk.js:2457:792)
    at div
    at t (http://127.0.0.1:5500/sdk/sdk.js:3482:17195)
    at n (http://127.0.0.1:5500/sdk/sdk.js:3292:355)
    at s (http://127.0.0.1:5500/sdk/sdk.js:3288:387)
    at i (http://127.0.0.1:5500/sdk/sdk.js:3286:390)
    at t (http://127.0.0.1:5500/sdk/sdk.js:2457:792)
    at div
    at div
    at div
    at t (http://127.0.0.1:5500/sdk/sdk.js:3482:16932)
    at t (http://127.0.0.1:5500/sdk/sdk.js:2457:792)
    at div
    at div
    at t (http://127.0.0.1:5500/sdk/sdk.js:3482:12607)
    at r (http://127.0.0.1:5500/sdk/sdk.js:2178:486)
    at t (http://127.0.0.1:5500/sdk/sdk.js:2457:792)
    at div
    at t (http://127.0.0.1:5500/sdk/sdk.js:3278:27358)
    at r (http://127.0.0.1:5500/sdk/sdk.js:2178:486)
    at n (http://127.0.0.1:5500/sdk/sdk.js:2172:2953)
    at t (http://127.0.0.1:5500/sdk/sdk.js:2457:792)
    at div
    at div
    at div
    at n (http://127.0.0.1:5500/sdk/sdk.js:2876:245)
    at a (http://127.0.0.1:5500/sdk/sdk.js:2264:1433)
    at t (http://127.0.0.1:5500/sdk/sdk.js:3254:6544)
    at r (http://127.0.0.1:5500/sdk/sdk.js:2178:486)
    at t (http://127.0.0.1:5500/sdk/sdk.js:2457:792)
    at t (http://127.0.0.1:5500/sdk/sdk.js:2451:428)
    at t (http://127.0.0.1:5500/sdk/sdk.js:3203:311)
    at n (http://127.0.0.1:5500/sdk/sdk.js:2262:981)
    at a (http://127.0.0.1:5500/sdk/sdk.js:2264:1433)
    at t (http://127.0.0.1:5500/sdk/sdk.js:2459:403)
    at n (http://127.0.0.1:5500/sdk/sdk.js:2172:2953)
    at div
```

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`
2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
2.0.2

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
		"type": "crud",
		"api": "/api/v1/svc/workload",
		"mode": "list",
		"placeholder": "当前组内, 还没有配置任何权限.",
		"syncLocation": false,
		"title": null,
		"listItem": {
		  "title": "$namespace",
		  "body": {
			"type": "cards",
		  }
		}
	}
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by agileago** [comment]
@2betop +1
