### ISSUE TITLE
使用富文本的对话框内表单,多次弹出时发生错误

### ISSUE THREAD

**Issue by JackyLui** [baidu/amis#5619]
使用富文本的对话框内表单,多次弹出时发生错误

对话框设定：
{
    "dialog": {
        "type": "dialog",
        "size": "full",
        "body": [
            {
                "type": "form",
                "title": "表单",
                "body": [
                    {
                        "type": "input-rich-text",
                        "label": "富文本",
                        "name": "content",
                    }
                ],
                "initApi": "get:/admin/cms/article/$id"
            }
        ],
    },
    "actionType": "dialog"
}

#错误信息：

TypeError: Cannot read properties of undefined (reading 'select')

    at t (http://localhost:8080/admin/vendor/amis2.3.1/tinymce.js:104:626)
    at t (http://localhost:8080/admin/vendor/amis2.3.1/sdk.js:2241:279)
    at div
    at t (http://localhost:8080/admin/vendor/amis2.3.1/sdk.js:3521:4545)
    at div
    at div

第一次弹出话框时正常,当再次弹出话框内时就会出现以上错误.
测试后发现"size": "full"时才会发生,"size": "lg"时没有问题.

**Comment by JackyLui** [comment]
drawer及dialog都有此問題.2.0版本有問題,1.10.2正常

**Comment by nabaonan** [comment]
#7346
