### ISSUE TITLE
使用 日期选择器 报错

### ISSUE THREAD

**Issue by hyzx86** [baidu/amis#6080]
#### 描述问题：

在 umi4 中 使用 日期选择器 报错， amis-editor 里面预览 也同样报错
可能不是 amis 问题，想知道怎么解决~~感谢！
#### 截图或视频：

日期范围选择器，和日期选择器都有这种情况
![image](https://user-images.githubusercontent.com/15613121/212723767-3e7d9abe-93b4-46ed-a746-04bbd849b0aa.png)

![image](https://user-images.githubusercontent.com/15613121/212723639-2f4793df-b065-4002-85b5-1a4810a66559.png)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
使用 umi4 
目前其它组件都正常，就日期选择器出问题

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

"amis": "2.6.1-alpha.0",
"amis-core": "2.6.1-alpha.0",
"amis-editor": "5.2.3-beta.16",
"amis-editor-core": "5.2.3-beta.16",
"amis-formula": "2.6.1-alpha.0",
"amis-ui": "2.6.1-alpha.0",

3. 粘贴有问题的完整 `amis schema` 代码：
``` json
{
  "type": "page",
  "regions": [
    "body",
    "toolbar",
    "header"
  ],
  "id": "u:4bea7b1f566c",
  "body": [
    {
      "type": "input-date",
      "label": "日期",
      "name": "date",
      "id": "u:fa2d6e1777d0"
    },
    {
      "type": "input-date-range",
      "label": "日期范围",
      "name": "date-range",
      "id": "u:d84aa503fddb"
    }
  ]
}
```

4. 操作步骤
预览后 ，点击选择日期，报如下错误

```
TypeError: currentDate.toObject is not a function

    at CustomDaysView (http://localhost:1688/mf-dep____vendor.a923b5f1.js:350773:28)
    at class_1 (http://localhost:1688/mf-dep____vendor.a923b5f1.js:226179:36)
    at CustomCalendarContainer (http://localhost:1688/mf-dep____vendor.a923b5f1.js:350702:47)
    at div
    at div
    at BaseDatePicker (http://localhost:1688/mf-dep____vendor.a923b5f1.js:350195:28)
    at class_1 (http://localhost:1688/mf-dep____vendor.a923b5f1.js:235882:36)
    at div
    at PopOver (http://localhost:1688/mf-dep____vendor.a923b5f1.js:225002:47)
    at class_1 (http://localhost:1688/mf-dep____vendor.a923b5f1.js:235882:36)
    at Position (http://localhost:1688/mf-dep____vendor.a923b5f1.js:224693:28)
    at Portal (http://localhost:1688/mf-dep____vendor.a923b5f1.js:1040733:24)
    at Overlay (http://localhost:1688/mf-dep____vendor.a923b5f1.js:224786:28)
    at div
    at DatePicker (http://localhost:1688/mf-dep____vendor.a923b5f1.js:334047:24)
    at class_1 (http://localhost:1688/mf-dep____vendor.a923b5f1.js:226179:36)
    at class_1 (http://localhost:1688/mf-dep____vendor.a923b5f1.js:235882:36)
    at div
    at DateControlRenderer (http://localhost:1688/mf-dep____vendor.a923b5f1.js:379761:42)
    at div
    at class_1 (http://localhost:1688/mf-dep____vendor.a923b5f1.js:228340:40)
    at class_1 (http://localhost:1688/mf-dep____vendor.a923b5f1.js:229645:32)
    at class_1 (http://localhost:1688/mf-dep____vendor.a923b5f1.js:222727:50)
    at SchemaRenderer (http://localhost:1688/mf-dep____vendor.a923b5f1.js:222061:28)
    at div
    at div
    at div
    at div
    at PageRenderer (http://localhost:1688/mf-dep____vendor.a923b5f1.js:394794:28)
    at StoreFactory (http://localhost:1688/mf-dep____vendor.a923b5f1.js:222803:36)
    at ScopedComponent (http://localhost:1688/mf-dep____vendor.a923b5f1.js:222650:32)
    at SchemaRenderer (http://localhost:1688/mf-dep____vendor.a923b5f1.js:222061:28)
    at RootRenderer (http://localhost:1688/mf-dep____vendor.a923b5f1.js:221707:24)
    at ImageGallery (http://localhost:1688/mf-dep____vendor.a923b5f1.js:336748:47)
    at class_1 (http://localhost:1688/mf-dep____vendor.a923b5f1.js:226179:36)
    at class_1 (http://localhost:1688/mf-dep____vendor.a923b5f1.js:235882:36)
    at Root (http://localhost:1688/mf-dep____vendor.a923b5f1.js:221586:42)
    at ScopedComponent (http://localhost:1688/mf-dep____vendor.a923b5f1.js:222650:32)
    at t (http://localhost:1688/mf-dep____vendor.a923b5f1.js:244058:180157)
    at div
    at div
    at div
    at t (http://localhost:1688/mf-dep____vendor.a923b5f1.js:244058:162627)
    at div
    at div
    at div
    at t (http://localhost:1688/mf-dep____vendor.a923b5f1.js:244058:349329)
    at div
    at div
    at div
    at FullScreen (http://localhost:1688/mf-dep____vendor.a923b5f1.js:1039992:21)
    at AmisEditor (http://localhost:1688/p__sys__page-editor__editor.async.js:1660:129)
    at Suspense
    at RemoteComponent (http://localhost:1688/mf-dep____vendor.a923b5f1.js:219386:25)
    at Outlet (http://localhost:1688/mf-dep____vendor.a923b5f1.js:1042229:26)
    at EmptyRoute (http://localhost:1688/src_umi_core_EmptyRoute_tsx.async.js:32:70)
    at Suspense
    at RemoteComponent (http://localhost:1688/mf-dep____vendor.a923b5f1.js:219386:25)
    at Outlet (http://localhost:1688/mf-dep____vendor.a923b5f1.js:1042229:26)
    at EmptyRoute (http://localhost:1688/src_umi_core_EmptyRoute_tsx.async.js:32:70)
    at Suspense
    at RemoteComponent (http://localhost:1688/mf-dep____vendor.a923b5f1.js:219386:25)
    at Outlet (http://localhost:1688/mf-dep____vendor.a923b5f1.js:1042229:26)
    at RenderContent (http://localhost:1688/src_umi_umi_ts.async.js:4897:124)
    at Exception (http://localhost:1688/umi__plugin-layout__Layout.async.js:34:12)
    at main
    at http://localhost:1688/mf-dep____vendor.a923b5f1.js:425905:7
    at http://localhost:1688/mf-dep____vendor.a923b5f1.js:425886:46
    at ErrorBoundary (http://localhost:1688/mf-dep____vendor.a923b5f1.js:86231:90)
    at WrapContent (http://localhost:1688/mf-dep____vendor.a923b5f1.js:68922:70)
    at div
    at section
    at http://localhost:1688/mf-dep____vendor.a923b5f1.js:425921:42
    at http://localhost:1688/mf-dep____vendor.a923b5f1.js:425886:46
    at div
    at BaseProLayout (http://localhost:1688/mf-dep____vendor.a923b5f1.js:68583:13)
    at ProviderChildren (http://localhost:1688/mf-dep____vendor.a923b5f1.js:414856:5)
    at LocaleReceiver (http://localhost:1688/mf-dep____vendor.a923b5f1.js:426912:5)
    at ConfigProvider
    at div
    at SWRConfig (http://localhost:1688/mf-dep____vendor.a923b5f1.js:1210676:13)
    at ConfigProVidContainer (http://localhost:1688/mf-dep____vendor.a923b5f1.js:77071:24)
    at FormProvider (http://localhost:1688/mf-dep____vendor.a923b5f1.js:952799:31)
    at LocaleProvider (http://localhost:1688/mf-dep____vendor.a923b5f1.js:427142:5)
    at ProviderChildren (http://localhost:1688/mf-dep____vendor.a923b5f1.js:414856:5)
    at LocaleReceiver (http://localhost:1688/mf-dep____vendor.a923b5f1.js:426912:5)
    at ConfigProvider
    at ProConfigProvider (http://localhost:1688/mf-dep____vendor.a923b5f1.js:77174:24)
    at ProviderChildren (http://localhost:1688/mf-dep____vendor.a923b5f1.js:414856:5)
    at LocaleReceiver (http://localhost:1688/mf-dep____vendor.a923b5f1.js:426912:5)
    at ConfigProvider
    at ProLayout (http://localhost:1688/mf-dep____vendor.a923b5f1.js:68870:28)
    at http://localhost:1688/umi__plugin-layout__Layout.async.js:209:66
    at Suspense
    at RemoteComponent (http://localhost:1688/mf-dep____vendor.a923b5f1.js:219386:25)
    at Routes (http://localhost:1688/mf-dep____vendor.a923b5f1.js:218899:76)
    at Router (http://localhost:1688/mf-dep____vendor.a923b5f1.js:1042252:15)
    at BrowserRoutes (http://localhost:1688/mf-dep____vendor.a923b5f1.js:218857:23)
    at FormProvider (http://localhost:1688/mf-dep____vendor.a923b5f1.js:952799:31)
    at LocaleProvider (http://localhost:1688/mf-dep____vendor.a923b5f1.js:427142:5)
    at ProviderChildren (http://localhost:1688/mf-dep____vendor.a923b5f1.js:414856:5)
    at LocaleReceiver (http://localhost:1688/mf-dep____vendor.a923b5f1.js:426912:5)
    at ConfigProvider
    at _LocaleContainer (http://localhost:1688/src_umi_umi_ts.async.js:3157:137)
    at Provider (http://localhost:1688/src_umi_umi_ts.async.js:1900:74)
    at InitialStateProvider (http://localhost:1688/src_umi_umi_ts.async.js:2151:131)
    at Provider (http://localhost:1688/src_umi_umi_ts.async.js:3706:34)
    at ProviderWrapper (http://localhost:1688/src_umi_umi_ts.async.js:3908:128)
    at r (http://localhost:1688/mf-dep____vendor.a923b5f1.js:1040052:7350)
    at Browser (http://localhost:1688/mf-dep____vendor.a923b5f1.js:218972:68) 
```

**Comment by hyzx86** [comment]
已解决，umi4 里面有一堆替换 moment  的操作，直接在 config文件注释掉 moment2dayjs 相关配置即可
