### ISSUE TITLE
按照 仓库首页的文档 windows下无法编译

### ISSUE THREAD

**Issue by hyzx86** [baidu/amis#6101]
#### 实现场景：
windows 下编译/打包
1.x版本正常，2.x 拆分包后就再也没跑起来过

#### 存在的问题：
编译报错...

#### 当前方案：
无..

```
 *  Executing task: yarn run build 

yarn run v1.22.19
$ npm run build --workspaces

> amis-formula@2.6.0 build
> npm run clean-dist && npm run genDoc && cross-env NODE_ENV=production rollup -c && cp src/doc.md lib/doc.md && cp src/doc.md esm/doc.md


> amis-formula@2.6.0 clean-dist
> rimraf lib/**


> amis-formula@2.6.0 genDoc
> ts-node ./scripts/genDoc.ts

公式文档生成 > E:\GitCodes\amis-projects\amis\packages\amis-formula\src\doc.ts
公式md生成 > E:\GitCodes\amis-projects\amis\packages\amis-formula\src\doc.md

./src/index.ts, ./src/doc.ts → lib...
created lib in 3.7s

./src/index.ts, ./src/doc.ts → esm...
created esm in 2.8s
'cp' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! Lifecycle script `build` failed with error: 
npm ERR! Error: command failed 
npm ERR!   in workspace: amis-formula@2.6.0 
npm ERR!   at location: E:\GitCodes\amis-projects\amis\packages\amis-formula 

> amis-core@2.6.0 build
> npm run clean-dist && NODE_ENV=production rollup -c

[..................] / : ERR!   at location: E:\GitCodes\amis-projects\amis\packages\amis-formula
> amis-core@2.6.0 clean-dist
> rimraf lib/** esm/**

'NODE_ENV' 不是内部或外部命令，也不是可运行的程序itCodes\amis-projects\amis\packages\amis-formula
或批处理文件。
npm ERR! Lifecycle script `build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: amis-core@2.6.0
npm ERR!   at location: E:\GitCodes\amis-projects\amis\packages\amis-core

> amis-ui@2.6.0 build
> npm run clean-dist && NODE_ENV=production rollup -c

[..................] / : ERR!   at location: E:\GitCodes\amis-projects\amis\packages\amis-core
> amis-ui@2.6.0 clean-dist
> rimraf lib/** esm/**

'NODE_ENV' 不是内部或外部命令，也不是可运行的程序itCodes\amis-projects\amis\packages\amis-core
或批处理文件。
npm ERR! Lifecycle script `build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: amis-ui@2.6.0
npm ERR!   at location: E:\GitCodes\amis-projects\amis\packages\amis-ui

> amis@2.6.0 build
> npm run clean-dist && sh build.sh

npm WARN ignoring workspace config at E:\GitCodes\amis-projects\amis\packages\amis/.npmrc ui
[..................] / : ERR!   at location: E:\GitCodes\amis-projects\amis\packages\amis-ui
> amis@2.6.0 clean-dist
> rimraf lib/** esm/**

'sh' 不是内部或外部命令，也不是可运行的程序: E:\GitCodes\amis-projects\amis\packages\amis-ui
或批处理文件。
npm ERR! Lifecycle script `build` failed with error:
npm ERR! Error: command failed
npm ERR!   in workspace: amis@2.6.0 
npm ERR!   at location: E:\GitCodes\amis-projects\amis\packages\amis
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

 *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command yarn run build" terminated with exit code: 1. 
 *  Terminal will be reused by tasks, press any key to close it. 

```

**Comment by hyzx86** [comment]
- - 目录中有空格，我上面的记录删减了

**Comment by nwind** [comment]
用 wsl 试试吧

**Comment by hyzx86** [comment]
Hi @nwind ,

wsl2 的ubuntu 装好了
但是 参考 仓库首页 的方式还是不行

`npm i --legacy-peer-deps `

node v14.20.1

是不是缺少什么全局包啊？

```
..........
npm WARN deprecated cryptiles@0.2.2: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@0.2.4: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm ERR! cb() never called!

npm ERR! This is an error with npm itself. Please report this error at:
npm ERR!     <https://npm.community>

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hyzx86/.npm/_logs/2023-02-20T10_10_12_908Z-debug.log
```

**Comment by hyzx86** [comment]
换了个 cnpm 试试~ 貌似有戏
npm install -g cnpm --registry=https://registry.npm.taobao.org

**Comment by hyzx86** [comment]
$ npm run start


控制台输出。。
```> hyzx86@LVPC:/mnt/e/GitCodes/amis-projects/amis$ npm run start

> aisuda@ start /mnt/e/GitCodes/amis-projects/amis
> vite


  VITE v3.2.5  ready in 30283 ms

  ➜  Local:   http://localhost:8888/
  ➜  Network: use --host to expose
7:28:02 PM [vite] Internal server error: [sass] Can't find stylesheet to import.
  ╷
6 │ @import '../../../node_modules/cropperjs/dist/cropper';
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  packages/amis-ui/scss/_thirds.scss 6:9         @import
  packages/amis-ui/scss/themes/_common.scss 1:9  @import
  packages/amis-ui/scss/themes/cxd.scss 5:9      root stylesheet
  Plugin: vite:css
  File: /mnt/e/GitCodes/amis-projects/amis/packages/amis-ui/scss/_thirds.scss:6:9
  Error: Can't find stylesheet to import.
    ╷
  6 │ @import '../../../node_modules/cropperjs/dist/cropper';
    │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
    packages/amis-ui/scss/_thirds.scss 6:9         @import
    packages/amis-ui/scss/themes/_common.scss 1:9  @import
    packages/amis-ui/scss/themes/cxd.scss 5:9      root stylesheet
      at Object.wrapException (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:1250:17)
      at /mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:71174:25
      at _wrapJsFunctionForAsync_closure.$protected (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:3841:15)
      at _wrapJsFunctionForAsync_closure.call$2 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:28694:12)
      at _awaitOnObject_closure.call$1 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:28682:32)
      at Object._rootRunUnary (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:4216:18)
      at StaticClosure.<anonymous> (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:100086:16)
      at _CustomZone.runUnary$2$2 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:30091:39)
      at _Future__propagateToListeners_handleValueCallback.call$0 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:29163:51)
      at Object._Future__propagateToListeners (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:4012:93)
```


![image](https://user-images.githubusercontent.com/15613121/220094367-4eaf9be7-93c6-49d4-9cd1-0b2842ab5bcf.png)

**Comment by xianlinzhang** [comment]
> $ npm run start
> 
> 控制台输出。。
> 
> ```
> 
> > aisuda@ start /mnt/e/GitCodes/amis-projects/amis
> > vite
> 
> 
>   VITE v3.2.5  ready in 30283 ms
> 
>   ➜  Local:   http://localhost:8888/
>   ➜  Network: use --host to expose
> 7:28:02 PM [vite] Internal server error: [sass] Can't find stylesheet to import.
>   ╷
> 6 │ @import '../../../node_modules/cropperjs/dist/cropper';
>   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   ╵
>   packages/amis-ui/scss/_thirds.scss 6:9         @import
>   packages/amis-ui/scss/themes/_common.scss 1:9  @import
>   packages/amis-ui/scss/themes/cxd.scss 5:9      root stylesheet
>   Plugin: vite:css
>   File: /mnt/e/GitCodes/amis-projects/amis/packages/amis-ui/scss/_thirds.scss:6:9
>   Error: Can't find stylesheet to import.
>     ╷
>   6 │ @import '../../../node_modules/cropperjs/dist/cropper';
>     │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     ╵
>     packages/amis-ui/scss/_thirds.scss 6:9         @import
>     packages/amis-ui/scss/themes/_common.scss 1:9  @import
>     packages/amis-ui/scss/themes/cxd.scss 5:9      root stylesheet
>       at Object.wrapException (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:1250:17)
>       at /mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:71174:25
>       at _wrapJsFunctionForAsync_closure.$protected (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:3841:15)
>       at _wrapJsFunctionForAsync_closure.call$2 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:28694:12)
>       at _awaitOnObject_closure.call$1 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:28682:32)
>       at Object._rootRunUnary (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:4216:18)
>       at StaticClosure.<anonymous> (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:100086:16)
>       at _CustomZone.runUnary$2$2 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:30091:39)
>       at _Future__propagateToListeners_handleValueCallback.call$0 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:29163:51)
>       at Object._Future__propagateToListeners (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:4012:93)
> ```
> 
> ![image](https://user-images.githubusercontent.com/15613121/220094367-4eaf9be7-93c6-49d4-9cd1-0b2842ab5bcf.png)

有解决这个问题吗？我也遇到同样的问题，用了wsl也不行 @nwind

**Comment by xianlinzhang** [comment]
![image](https://user-images.githubusercontent.com/30235909/236595309-37a89d6a-6170-4f76-98e7-3b83ec55fb89.png)
代码是tag v2.9.0

**Comment by ziBLan** [comment]
win 下 pakage文件里cp 改成 copy ， NODE_EN 前面加上cross-env 就好了

**Comment by ziBLan** [comment]
> #### 实现场景：
> windows 下编译/打包 1.x版本正常，2.x 拆分包后就再也没跑起来过
> 
> #### 存在的问题：
> 编译报错...
> 
> #### 当前方案：
> 无.. npm run build 输出如下
> 
> ```
>  *  Executing task: yarn run build 
> 
> yarn run v1.22.19
> $ npm run build --workspaces
> 
> > amis-formula@2.6.0 build
> > npm run clean-dist && npm run genDoc && cross-env NODE_ENV=production rollup -c && cp src/doc.md lib/doc.md && cp src/doc.md esm/doc.md
> 
> 
> > amis-formula@2.6.0 clean-dist
> > rimraf lib/**
> 
> 
> > amis-formula@2.6.0 genDoc
> > ts-node ./scripts/genDoc.ts
> 
> 公式文档生成 > E:\GitCodes\amis-projects\amis\packages\amis-formula\src\doc.ts
> 公式md生成 > E:\GitCodes\amis-projects\amis\packages\amis-formula\src\doc.md
> 
> ./src/index.ts, ./src/doc.ts → lib...
> created lib in 3.7s
> 
> ./src/index.ts, ./src/doc.ts → esm...
> created esm in 2.8s
> 'cp' 不是内部或外部命令，也不是可运行的程序
> 或批处理文件。
> npm ERR! Lifecycle script `build` failed with error: 
> npm ERR! Error: command failed 
> npm ERR!   in workspace: amis-formula@2.6.0 
> npm ERR!   at location: E:\GitCodes\amis-projects\amis\packages\amis-formula 
> 
> > amis-core@2.6.0 build
> > npm run clean-dist && NODE_ENV=production rollup -c
> 
> [..................] / : ERR!   at location: E:\GitCodes\amis-projects\amis\packages\amis-formula
> > amis-core@2.6.0 clean-dist
> > rimraf lib/** esm/**
> 
> 'NODE_ENV' 不是内部或外部命令，也不是可运行的程序itCodes\amis-projects\amis\packages\amis-formula
> 或批处理文件。
> npm ERR! Lifecycle script `build` failed with error:
> npm ERR! Error: command failed
> npm ERR!   in workspace: amis-core@2.6.0
> npm ERR!   at location: E:\GitCodes\amis-projects\amis\packages\amis-core
> 
> > amis-ui@2.6.0 build
> > npm run clean-dist && NODE_ENV=production rollup -c
> 
> [..................] / : ERR!   at location: E:\GitCodes\amis-projects\amis\packages\amis-core
> > amis-ui@2.6.0 clean-dist
> > rimraf lib/** esm/**
> 
> 'NODE_ENV' 不是内部或外部命令，也不是可运行的程序itCodes\amis-projects\amis\packages\amis-core
> 或批处理文件。
> npm ERR! Lifecycle script `build` failed with error:
> npm ERR! Error: command failed
> npm ERR!   in workspace: amis-ui@2.6.0
> npm ERR!   at location: E:\GitCodes\amis-projects\amis\packages\amis-ui
> 
> > amis@2.6.0 build
> > npm run clean-dist && sh build.sh
> 
> npm WARN ignoring workspace config at E:\GitCodes\amis-projects\amis\packages\amis/.npmrc ui
> [..................] / : ERR!   at location: E:\GitCodes\amis-projects\amis\packages\amis-ui
> > amis@2.6.0 clean-dist
> > rimraf lib/** esm/**
> 
> 'sh' 不是内部或外部命令，也不是可运行的程序: E:\GitCodes\amis-projects\amis\packages\amis-ui
> 或批处理文件。
> npm ERR! Lifecycle script `build` failed with error:
> npm ERR! Error: command failed
> npm ERR!   in workspace: amis@2.6.0 
> npm ERR!   at location: E:\GitCodes\amis-projects\amis\packages\amis
> error Command failed with exit code 1.
> info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
> 
>  *  The terminal process "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -Command yarn run build" terminated with exit code: 1. 
>  *  Terminal will be reused by tasks, press any key to close it. 
> ```

1

**Comment by xianlinzhang** [comment]
> win 下 pakage文件里cp 改成 copy ， NODE_EN 前面加上cross-env 就好了

嗯，这样可以解决

**Comment by xianlinzhang** [comment]
> > $ npm run start
> > 控制台输出。。
> > ```
> > 
> > > aisuda@ start /mnt/e/GitCodes/amis-projects/amis
> > > vite
> > 
> > 
> >   VITE v3.2.5  ready in 30283 ms
> > 
> >   ➜  Local:   http://localhost:8888/
> >   ➜  Network: use --host to expose
> > 7:28:02 PM [vite] Internal server error: [sass] Can't find stylesheet to import.
> >   ╷
> > 6 │ @import '../../../node_modules/cropperjs/dist/cropper';
> >   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >   ╵
> >   packages/amis-ui/scss/_thirds.scss 6:9         @import
> >   packages/amis-ui/scss/themes/_common.scss 1:9  @import
> >   packages/amis-ui/scss/themes/cxd.scss 5:9      root stylesheet
> >   Plugin: vite:css
> >   File: /mnt/e/GitCodes/amis-projects/amis/packages/amis-ui/scss/_thirds.scss:6:9
> >   Error: Can't find stylesheet to import.
> >     ╷
> >   6 │ @import '../../../node_modules/cropperjs/dist/cropper';
> >     │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> >     ╵
> >     packages/amis-ui/scss/_thirds.scss 6:9         @import
> >     packages/amis-ui/scss/themes/_common.scss 1:9  @import
> >     packages/amis-ui/scss/themes/cxd.scss 5:9      root stylesheet
> >       at Object.wrapException (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:1250:17)
> >       at /mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:71174:25
> >       at _wrapJsFunctionForAsync_closure.$protected (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:3841:15)
> >       at _wrapJsFunctionForAsync_closure.call$2 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:28694:12)
> >       at _awaitOnObject_closure.call$1 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:28682:32)
> >       at Object._rootRunUnary (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:4216:18)
> >       at StaticClosure.<anonymous> (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:100086:16)
> >       at _CustomZone.runUnary$2$2 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:30091:39)
> >       at _Future__propagateToListeners_handleValueCallback.call$0 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:29163:51)
> >       at Object._Future__propagateToListeners (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:4012:93)
> > ```
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/15613121/220094367-4eaf9be7-93c6-49d4-9cd1-0b2842ab5bcf.png)
> 
> 有解决这个问题吗？我也遇到同样的问题，用了wsl也不行 @nwind

我这个问题是node-sass 没有下载下来

解决方案：
https://stackoverflow.com/questions/58273617/unable-to-download-node-module

**Comment by ziBLan** [comment]
> > > $ npm run start
> > > 控制台输出。。
> > > ```
> > > 
> > > > aisuda@ start /mnt/e/GitCodes/amis-projects/amis
> > > > vite
> > > 
> > > 
> > >   VITE v3.2.5  ready in 30283 ms
> > > 
> > >   ➜  Local:   http://localhost:8888/
> > >   ➜  Network: use --host to expose
> > > 7:28:02 PM [vite] Internal server error: [sass] Can't find stylesheet to import.
> > >   ╷
> > > 6 │ @import '../../../node_modules/cropperjs/dist/cropper';
> > >   │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >   ╵
> > >   packages/amis-ui/scss/_thirds.scss 6:9         @import
> > >   packages/amis-ui/scss/themes/_common.scss 1:9  @import
> > >   packages/amis-ui/scss/themes/cxd.scss 5:9      root stylesheet
> > >   Plugin: vite:css
> > >   File: /mnt/e/GitCodes/amis-projects/amis/packages/amis-ui/scss/_thirds.scss:6:9
> > >   Error: Can't find stylesheet to import.
> > >     ╷
> > >   6 │ @import '../../../node_modules/cropperjs/dist/cropper';
> > >     │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> > >     ╵
> > >     packages/amis-ui/scss/_thirds.scss 6:9         @import
> > >     packages/amis-ui/scss/themes/_common.scss 1:9  @import
> > >     packages/amis-ui/scss/themes/cxd.scss 5:9      root stylesheet
> > >       at Object.wrapException (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:1250:17)
> > >       at /mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:71174:25
> > >       at _wrapJsFunctionForAsync_closure.$protected (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:3841:15)
> > >       at _wrapJsFunctionForAsync_closure.call$2 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:28694:12)
> > >       at _awaitOnObject_closure.call$1 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:28682:32)
> > >       at Object._rootRunUnary (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:4216:18)
> > >       at StaticClosure.<anonymous> (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:100086:16)
> > >       at _CustomZone.runUnary$2$2 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:30091:39)
> > >       at _Future__propagateToListeners_handleValueCallback.call$0 (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:29163:51)
> > >       at Object._Future__propagateToListeners (/mnt/e/GitCodes/amis-projects/amis/node_modules/.store/sass@1.58.3/node_modules/sass/sass.dart.js:4012:93)
> > > ```
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/15613121/220094367-4eaf9be7-93c6-49d4-9cd1-0b2842ab5bcf.png)
> > 
> > 
> > 有解决这个问题吗？我也遇到同样的问题，用了wsl也不行 @nwind
> 
> 我这个问题是node-sass 没有下载下来
> 
> 解决方案： https://stackoverflow.com/questions/58273617/unable-to-download-node-module

vite build 可以构建出 文档和编辑器两个入口的静态文件吗

**Comment by hupanfeng** [comment]
就没有人管这个问题了莫？百度人人苹果？

**Comment by hupanfeng** [comment]
在顶层package.json里加入    "cross-env": "^10.1.0"可以解决cross-env缺失的问题，但 cp命令得换成copy。

**Comment by hyzx86** [comment]
实在不行 换成 麒麟 Linux 或者 跑个 WSL吧 😂
