### ISSUE TITLE
富文本组件使用问题

### ISSUE THREAD

**Issue by amisadmin** [baidu/amis#6212]
#### 描述问题：

在使用富文本的表单页面,有一定的几率出现严重加载错误,
页面加载失败,浏览器提示.
```
TypeError: Cannot read properties of undefined (reading 'parse')

    at t (https://cdn.jsdelivr.net/npm/amis@2.7.2/sdk/tinymce.js:110:652)
    at t (https://cdn.jsdelivr.net/npm/amis@2.7.2/sdk/sdk.js:2240:279)
```
- 测试了最新js sdk 2.7.2版本,其他版本也存在同样的问题. 

- 有问题的完整 `amis schema` 代码：
```
{
  "type": "page",
  "body": {
    "type": "form",
    "title": "",
    "body": [
      {
        "type": "input-rich-text",
        "name": "body",
        "label": "文案内容",
        "value": "",
        "required": false,
        "receiver": "post:/api/v1/addons/qiniu_oss/upload",
        "videoReceiver": "post:/api/mkadmin/file/upload"
      }
    ],
    "api": {
      "url": "/api/mkadmin/PushArticle/form/apps.pusharitcle.admin/ArticlePreviewAdmin/api",
      "method": "POST"
    },
    "initApi": {
      "url": "/api/mkadmin/PushArticle/form/apps.pusharitcle.admin/ArticlePreviewAdmin/api",
      "method": "GET"
    }
  }
}
```

- 操作步骤
多次刷新页面,或者从其他页面跳转到有富文本表单的页面都有一定的几率报错.

**Comment by taoyao-code** [comment]
请问高度能设置吗？目前我这边高度无法正常设置。2.7.2 npm版本

**Comment by UltramanWeiLai** [comment]
这个问题解决了吗？

**Comment by UltramanWeiLai** [comment]
https://github.com/baidu/amis/issues/5850
我在这个 issue 里面找到了问题的原因，通过特殊的方法进行规避

**Comment by nabaonan** [comment]
#7346
