### ISSUE TITLE
ant design pro引入amis，编译报错。

### ISSUE THREAD

**Issue by rodchen-king** [baidu/amis#652]
error  in ./node_modules/monaco-editor/esm/vs/editor/contrib/suggest/media/suggest.css

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader-1/index.js):
TypeError: exports[name].indexOf is not a function
    at exportScopedName (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:50:25)
    at localizeNode (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:64:28)
    at Array.map (<anonymous>)
    at localizeNode (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:60:38)
    at traverseNode (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:78:20)
    at Array.map (<anonymous>)
    at traverseNode (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:84:38)
    at Array.map (<anonymous>)
    at traverseNode (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:84:38)
    at callback (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:103:25)
    at callback (E:\workspace\antdesign-pro-amis\node_modules\postcss\lib\container.es6:198:28)
    at callback (E:\workspace\antdesign-pro-amis\node_modules\postcss\lib\container.es6:109:26)
    at Root.each (E:\workspace\antdesign-pro-amis\node_modules\postcss\lib\container.es6:77:22)
    at Root.walk (E:\workspace\antdesign-pro-amis\node_modules\postcss\lib\container.es6:108:21)
    at Root.walkRules (E:\workspace\antdesign-pro-amis\node_modules\postcss\lib\container.es6:196:25)
    at E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\node_modules\postcss-modules-scope\lib\index.js:101:9
    at runLoaders (E:\workspace\antdesign-pro-amis\node_modules\webpack\lib\NormalModule.js:316:20)
    at E:\workspace\antdesign-pro-amis\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at E:\workspace\antdesign-pro-amis\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (E:\workspace\antdesign-pro-amis\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at Object.<anonymous> (E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\lib\loader.js:44:18)
    at E:\workspace\antdesign-pro-amis\node_modules\css-loader-1\lib\processCss.js:216:4

 @ ./node_modules/monaco-editor/esm/vs/editor/contrib/suggest/suggestWidget.js 25:0-29
 @ ./node_modules/monaco-editor/esm/vs/editor/contrib/suggest/suggestController.js
 @ ./node_modules/monaco-editor/esm/vs/editor/editor.all.js
 @ ./node_modules/monaco-editor/esm/vs/editor/edcore.main.js
 @ ./node_modules/monaco-editor/esm/vs/editor/editor.main.js
 @ ./node_modules/amis/lib/components/Editor.js
 @ ./node_modules/amis/lib/components/index.js
 @ ./node_modules/amis/lib/index.js
 @ ./src/pages/List/BasicList.js
 @ ./src/pages/.umi/router.js
 @ ./src/pages/.umi/umi.js
 @ multi ./node_modules/af-webpack/lib/webpackHotDevClient.js ./src/pages/.umi/umi.js

**Comment by 2betop** [comment]
这个 amis 没什么关系啊，报错也是  monaco-editor 的部分

**Comment by rodchen-king** [comment]
> 这跟 amis 没什么关系啊，报错也是 monaco-editor 的部分

![image](https://user-images.githubusercontent.com/19780441/83841366-4b7ee700-a733-11ea-9628-91e9a57021fc.png)
就是因为用了这个amis，然后不清楚内部引用的什么，报错了。

**Comment by 2betop** [comment]
我不清楚 ant design pro 用的什么打包工具，如果也是 webpack ，可以参考这里面的配置: https://github.com/fex-team/amis-admin/blob/webpack/webpack.config.js

**Comment by yiyi17** [comment]
![image](https://user-images.githubusercontent.com/25927480/161518918-e6227b86-d97f-415e-9c88-81fd3cac48d2.png)
样式库default.css 添加上空格就好了，样式拷贝下来

**Comment by yiyi17** [comment]
![image](https://user-images.githubusercontent.com/25927480/161518918-e6227b86-d97f-415e-9c88-81fd3cac48d2.png)
样式库default.css 添加上空格就好了，样式拷贝下来
