### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'parse')

### ISSUE THREAD

**Issue by xinxinxinxinwu** [baidu/amis#7108]
使用input-rich-text组建默认的Tinymce富文本编辑器时会出现以下错误
`
TypeError: Cannot read properties of undefined (reading 'parse')
    at setContentString (tinymce.js:12893:55)
    at eval (tinymce.js:12921:1)
    at Optional.map (tinymce.js:222:1)
    at setContentInternal (tinymce.js:12917:1)
    at Object.setContent (tinymce.js:17836:1)
    at setContent$2 (tinymce.js:18005:1)
    at eval (tinymce.js:18748:1)
    at Object.map (tinymce.js:6259:1)
    at setContent (tinymce.js:18747:1)
    at Editor.setContent (tinymce.js:29825:1)
`
#### 如何复现
刷新页面时会偶现这个错误

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
"amis": "^2.8.0",

3. 粘贴有问题的完整 `amis schema` 代码：
```
import schme2component from '@/utils/schme2component';
import getInformationCreate from "@/pages/cms/information/information-create";
import getInformationConfig from "@/pages/cms/information/information-config";
import {STORAGE_SHOP_INFO_KEY} from "@/utils/constant";
import getInformationColumn from "@/pages/cms/column/InformationColumnSelect";

const status = [
  {
    label: '已创建',
    value: 'created',
  },
  {
    label: '待发布',
    value: 'pending_publish',
  },
  {
    label: '已发布',
    value: 'published',
  },
];

const schme = (props) => {
  const shopInfo = JSON.parse(window.localStorage.getItem(STORAGE_SHOP_INFO_KEY) || '{}');
  const { shopSites: { isPackagingMall } } = props;
  return {
    type: 'page',
    title: '资讯管理',
    style: {background: '#fff'},
    body: {
      type: 'wrapper',
      body:
        {
          type: 'crud',
          name: 'information_list',
          id: 'information_list',
          api: {
            method: 'post',
            url: '/api/admin/rest/cms/information/listPage',
            requestAdaptor: function (api: any) {
              if (api.data.informationColumnId) {
                api.data.informationColumnIds = [api.data.informationColumnId]
                return api;
              }
            },
          },
          defaultParams: {
            pageIndex: 1,
            pageSize: 10
          },
          pageField: 'pageIndex',
          perPageField: 'pageSize',
          syncLocation: false,
          autoGenerateFilter: true,
          filter: {
            actions: [
              {
                type: 'reset',
                label: '重置',
              },
              {
                type: 'submit',
                label: '查询',
                level: "primary",
              }
            ],
            columnCount: 4,
            mode: 'horizontal',
            title: "筛选查询",
            submitText: "",
            body: [
              {
                name: 'title',
                type: 'input-text',
                label: '资讯标题',
                clearable: true,
                placeholder: "请输入标题关键字",
                minLength: 1,
                maxLength: 50,
              },
              {
                name: 'status',
                type: 'select',
                label: '资讯状态',
                clearable: true,
                searchable: true,
                placeholder: "请选择资讯状态",
                options: status,
              },
              isPackagingMall && getInformationColumn(props,false, true),
              {
                type: "input-datetime",
                name: "firstPublishTime",
                label: "首次发布时间",
                format: "YYYY-MM-DD HH:mm:ss",
              },
            ]
          },
          footerToolbar: [
            'statistics',
            'switch-per-page',
            'pagination',
          ],
          headerToolbar: [
            {
              type: 'button',
              actionType: 'drawer',
              label: '新增资讯',
              visibleOn: 'userAccessInfo.includes("CMS:INFORMATION:CREATE")',
              icon: 'fa fa-plus pull-left',
              primary: true,
              drawer: getInformationCreate(props),
            }
          ],
          "quickSaveItemApi": {
            method: 'post',
            url: '/api/admin/rest/cms/information/packaging/upsert',
          },
          columns: [
            {
              name: 'index',
              label: '序号',
            },
            {
              name: 'informationId',
              label: '资讯ID',
            },
            {
              name: 'title',
              label: '资讯标题',
            },
            {
              type: 'link',
              name: 'url',
              label: '资讯地址',
            },
            {
              name: 'status',
              label: '状态',
            },
            isPackagingMall && {
              type: "nested-select",
              name: 'informationColumnId',
              label: '栏目分类',
              "disabled": true,
              source: {
                method: 'post',
                url: '/api/admin/rest/cms/manage/information/column/query',
                adaptor: 'return {\n    ...payload,\n    option: payload.data\n}'
              }
            },
            {
              name: 'updateName',
              label: '最后修改人',
            },
            {
              name: 'createAt',
              label: '创建时间',
            },
            {
              name: 'firstPublishTime',
              label: '首次发布时间',
            },
            {
              name: 'publishTime',
              label: '最近发布时间',
            },
            {
              type: 'operation',
              label: '操作',
              width: 200,
              buttons: [
                {
                  label: '预览',
                  type: 'button',
                  level: 'link',
                  visibleOn: 'userAccessInfo.includes("CMS:INFORMATION:PREVIEW")',
                  actionType: 'ajax',
                  api: {
                    url: "/api/admin/rest/cms/page/preview",
                    data: {
                      informationId: "${informationId}",
                      salesTerminal: "${salesTerminal}",
                      pageType: "information_page"
                    },
                    adaptor: function (payload: any, res: any, api: any) {
                      const {data} = payload || {};
                      const {data: req} = api || {};
                      if (data && data.previewUrl) {
                        window.open(`${data.previewUrl}${req.informationId}?type=1&locale=${shopInfo.lang}`)
                      }
                      return payload;
                    }
                  },
                },
                {
                  label: '装饰',
                  type: 'button',
                  // actionType: "link",
                  actionType: "drawer",
                  visibleOn: 'userAccessInfo.includes("CMS:INFORMATION:CONFIG")',
                  level: 'warning',
                  drawer: getInformationConfig(props),
                  // link: "./information/config/${informationId}?informationId=${informationId}",
                },
                {
                  label: '发布',
                  type: 'button',
                  actionType: 'dialog',
                  visibleOn: 'status != "已发布" && userAccessInfo.includes("CMS:INFORMATION:PUBLISH")',
                  level: 'success',
                  dialog: {
                    title: "提示",
                    actions: [
                      {
                        "label": "确认",
                        "actionType": "ajax",
                        "reload": "information_list",
                        "close": true,
                        "primary": true,
                        "type": "button",
                        api: {
                          method: 'post',
                          url: '/api/admin/rest/cms/information/publish',
                          data: {
                            "informationId": "${informationId}",
                          },
                        },
                        messages: {
                          success: "发布成功",
                          failed: "发布失败"
                        }
                      }
                    ],
                    body: '确认要发布吗?'
                  },
                },
                {
                  label: '删除',
                  type: 'button',
                  actionType: 'dialog',
                  visibleOn: 'userAccessInfo.includes("CMS:INFORMATION:DELETE")',
                  level: 'danger',
                  dialog: {
                    title: "提示",
                    actions: [
                      {
                        "label": "确认",
                        "actionType": "ajax",
                        "reload": "information_list",
                        "close": true,
                        "primary": true,
                        "type": "button",
                        api: {
                          method: 'post',
                          url: '/api/admin/rest/cms/information/delete',
                          data: {
                            "informationId": "${informationId}",
                          },
                        },
                        messages: {
                          success: "删除成功",
                        }
                      }
                    ],
                    body: '确认要删除吗?'
                  },
                },
              ],
            },
          ],
        },
    }
  }
};

export default schme2component(schme);

```

4. 操作步骤
刷新页面时，再打开富文本编辑器弹窗，会偶现这个问题

5: [Tinymce的issues中看到的处理方式](https://github.com/tinymce/tinymce/issues/3413)

**Comment by nabaonan** [comment]
同样遇到相同的错误，

弹框里用富文本，

复现步骤：

使用apifox模拟接口
延时设置为100毫秒
`fox.mockResponse.setDelay(100)`

接口返回结构如下：
```json
{
    "code": 0,
    "result": {
        "name": "<p>66666575675675675675675675675676666657567567567567567567567567666665756756756756756756756756766666575675675675675675675675676666657567567567567567567567567666665756756756756756756756756766666575675675675675675675675676666657567567567567567567567567666665756756756756756756756756766666575675675675675675675675676666657567567567567567567567567666665756756756756756756756756766666575675675675675675675675676666657567567567567567567567567666665756756756756756756756756766666575675675675675675675675676666657567567567567567567567567666665756756756756756756756756766666575675675675675675675675676666657567567567567567567567567</p>"
    }
}

```

页面配置如下：
```json
{
  "type": "page",
  "id": "u:69d10e15cac3",
  "css": {
  },
  "body": [
    {
      "type": "tpl",
      "tpl": "Hello 梧桐",
      "wrapperComponent": "",
      "inline": false,
      "id": "u:1b09c323412c"
    },
    {
      "type": "button",
      "label": "按钮",
      "onEvent": {
        "click": {
          "actions": [
            {
              "actionType": "dialog",
              "dialog": {
                "type": "dialog",
                "title": "弹框标题",
                "body": [
                  {
                    "type": "page",
                    "id": "u:7b3e56e90c97",
                    "css": {
                    },
                    "body": [
                      {
                        "type": "form",
                        "id": "activityForm",
                        "debug": false,
                        "preventEnterSubmit": true,
                        "mode": "horizontal",
                        "horizontal": {
                          "leftFixed": "normal"
                        },
                        "comments": "data 属性可以初始化数据，也可以用于设置固定值",
                        "data": {
                        },
                      
                        "canAccessSuperData": false,
                        "trimValues": true,
                        "body": [
                          {
                            "type": "radios",
                            "name": "homepageNewsInfo.publisher",
                            "required": true,
                            "id": "u:b9127765b9c9",
                            "label": "发布人",
                            "options": [
                              {
                                "label": "个人名义",
                                "value": "0"
                              },
                              {
                                "label": "部门名义",
                                "value": "1"
                              },
                              {
                                "label": "自定义",
                                "value": "2"
                              }
                            ],
                            "value": "0"
                          },
                          {
                            "type": "input-rich-text",
                            "id": "u:fb7b8855ae3a",
                            "name": "content",
                            "required": true,
                            "options": {
                              "plugins": "advlist,autolink,link,image,lists,charmap,preview,anchor,pagebreak,searchreplace,wordcount,visualblocks,visualchars,code,fullscreen,insertdatetime,media,nonbreaking,table,emoticons,template,help",
                              "toolbar": "undo redo formatselect bold italic backcolor alignleft aligncenter alignright alignjustify bullist numlist outdent indent removeformat help",
                              "menubar": true,
                              "validations": {
                                "maxLength": 10000
                              },
                              "messages": {
                                "maxLength": "最大长度不能超过10000个字符"
                              }
                            },
                            "receiver": "/api/upload/image",
                            "vendor": "tinymce",
                            "disabledOn": "${static}"
                          }
                        ],
                        "wrapWithPanel": false,
                        "messages": {
                          "validateFailed": "" //配置为空则不弹框提示
                        },
                        "reload": "crud",
                        "initApi": {
                          "url": "http://127.0.0.1:4523/m1/1025967-0-default/test",
                          "method": "get",
                          "data": {
                            "id": "${id}"
                          },
                          "messages": {
                            "validateFailed": "" //配置为空则不弹框提示
                          },
                          "requestAdaptor": "",
                          "adaptor": "console.log('!!!!!!',payload)\n\n\nreturn {\n  ...payload,\n  data: {\n    content: payload.result.name\n  }\n}",
                          "sendOn": ""
                        }
                      }
                    ],
                    "data": {
                      "imageBaseUrl": "/api/village_household/datatool/v1/public_controller/image_preview?filename=",
                   
                      
                     
                    },
                    "asideResizor": false,
                    "pullRefresh": {
                      "disabled": true
                    },
                    "onEvent": {
                      "init": {
                        "weight": 0,
                        "actions": [
                          {
                            "actionType": "nonstatic",
                            "componentId": "activityForm",
                            "expression": "${!static}"
                          },
                          {
                            "actionType": "static",
                            "componentId": "activityForm",
                            "expression": "${static}"
                          }
                        ]
                      }
                    },
                    "style": {
                      "boxShadow": "var(--shadows-shadow-none)"
                    }
                  }
                ],
                "showCloseButton": true,
                "showErrorMsg": true,
                "showLoading": true,
                "className": "app-popover",
                "id": "u:d96926409092"
              }
            }
          ]
        }
      },
      "id": "u:16648c44d39c"
    }
  ],
  "data": {
   
  
  },
  "asideResizor": false,
  "style": {
    "boxShadow": "var(--shadows-shadow-none)"
  },
  "pullRefresh": {
    "disabled": true
  }
}

```

看issue中有很多这个报错，官方还在跟进么？

**Comment by nabaonan** [comment]
偶现，但是比较频繁能复现，可能富文本没有准备好初始化就进行赋值导致

**Comment by nabaonan** [comment]
我提了一个pr #7346    加了个延时，本地试了一下没啥问题，暂时没找到太好的方案

**Comment by Tumbling-Clouds** [comment]
我也遇到了这个错误,但我的问题是webpack4的node_modules构建树没有扁平化管理出现了多个monaco-editor,node_modules/amis-ui/esm/components/Editor.js中源码Editor.prototype.loadMonaco = function () {
        var _this = this;
        // 由于 require.config({'vs/nls': { availableLanguages: { '*': 'xxxx' }}}) 只能在初始化之前设置有用，所以这里只能用全局变量的方式来设置。
        // 另外此方式只是针对 jssdk 和平台有效，对于其他方式还需要再想想。
        window.__amis_monaco_editor_locale = this.props.locale;
        import('monaco-editor').then(function (monaco) { return _this.initMonaco(monaco); });
    };
读取import('monaco-editor')失败导致的报错
