### ISSUE TITLE
SDK版3.1.1diff-editor编辑器报错不显示内容

### ISSUE THREAD

**Issue by czhlin** [baidu/amis#7323]
#### 描述问题：

SDK版3.1.1diff-editor编辑器报错不显示内容

#### 报错信息：

loader.js:1 Uncaught SyntaxError: Unexpected token '<' (at loader.js:1:1)
sdk.js:4175 Uncaught TypeError: Cannot read properties of undefined (reading 'config')
    at sdk.js:4175:6029
    at amis.require.loadJs.onload (sdk.js:4175:6564)

#### html
```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="/amis/sdk.css" />
  <link rel="stylesheet" href="/amis/helper.css" />
  <link rel="stylesheet" href="/amis/iconfont.css" />
</head>
<body>
  <div id="amis"></div>
  <script src="/amis/sdk.js"></script>
  <script>
    (function () {
        let amis = window.amisRequire('amis/embed');
        // 通过替换下面这个配置来生成不同页面
        let amisJSON = {
  "type": "page",
  "body": {
    "type": "form",
    "api": "https://3xsw4ap8wah59.cfc-execute.bj.baidubce.com/api/amis-mock/mock2/form/saveForm",
    "body": [
      {
        "type": "diff-editor",
        "name": "diff",
        "label": "Diff-Editor",
        "diffValue": "hello world",
        "value": "hello"
      }
    ]
  }
};
        let amisScoped = amis.embed('#amis', amisJSON);
      })();
  </script>
</body>
</html>
```
#### package.json
````json
 "dependencies": {
        "amis": "^3.1.1",
        "amis-ui": "^3.1.1",
}
````

**Comment by czhlin** [comment]
### 问题找到了
![image](https://github.com/baidu/amis/assets/56159557/7f60a6a0-221d-419d-8632-ba7843ed2032)
需要引入thirds文件目录
### 优化建议
thirds文件目录内容能集成到sdk.js中

**Comment by 2betop** [comment]
如果都集成在 sdk.js 的，那个文件体积太大，所以特意拆包异步按需加载，比如 chart, rich-text, editor, video 等等
