### ISSUE TITLE
bug-i18n

### ISSUE THREAD

**Issue by mathYang1224** [baidu/amis#7511]
#### 描述问题：

升级到3.2.0版本之后时不时总弹窗i18n的编译错误

#### 截图或视频：

![image](https://github.com/baidu/amis/assets/45762245/12a7652f-578a-482a-837a-3135da6c83cd)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
3.2.0

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
3.2.0
3. 粘贴有问题的完整 `amis schema` 代码：
```
 任何schema都会有这个问题
```

4. 操作步骤
请简单描述一下复现的操作步骤...
本地开发环境复现，打包之后不存在

**Comment by 2betop** [comment]
看起来跟 amis 没关系，能否提供问题仓库？

**Comment by mathYang1224** [comment]
不影响生产，这个问题先不排查了😜ོ，多谢回复





------------------ Original ------------------
From: liaoxuezhi ***@***.***&gt;
Date: Fri,Jul 28,2023 10:14 AM
To: baidu/amis ***@***.***&gt;
Cc: mathYang1224 ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [baidu/amis] bug-i18n (Issue #7511)





 
看起来跟 amis 没关系，能否提供问题仓库？

**Comment by clh8801** [comment]
遇到同样的问题
Script at URL "http://localhost:3000/js/plugins/help/js/i18n/keynav/en.js" failed to load
    at handleError (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:252:58)
    at eval (webpack-internal:///./node_modules/webpack-dev-server/client/overlay.js:275:7)
