### ISSUE TITLE
不能在remix项目中正常使用amis组件

### ISSUE THREAD

**Issue by s8186255** [baidu/amis#7656]
代码：
import {render as renderAsAmis} from 'amis';
const schema = {
  "type": "page",
  "title": "标题",
  "body": "Hello World!"
};

export default function() {
    return renderAsAmis(schema);
}

错误：
my-remix-app/node_modules/amis-core/lib/utils/debug.js:274
var amisHoverBox = document.createElement('div');
                   ^
ReferenceError: document is not defined
    at Object.<anonymous> (/home/andrew/andrew-project/kcy/my-remix-app/node_modules/amis-core/lib/utils/debug.js:274:20)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Function.Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/home/andrew/andrew-project/kcy/my-remix-app/node_modules/amis-core/lib/utils/api.js:23:13)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1308:10)

**Comment by 2betop** [comment]
请提供一个问题仓库
