### ISSUE TITLE
crud导出csv或者导出excel报错

### ISSUE THREAD

**Issue by wnki** [baidu/amis#8037]
#### 描述问题：

crud导出csv或者导出excel报错

#### 截图或视频：

index.js:1281 TypeError: ExcelJS.Workbook is not a constructor
    at exportExcel.js:206:32
    at step (tslib.es6.js:147:23)
    at Object.next (tslib.es6.js:128:53)
    at tslib.es6.js:121:71
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:117:12)
    at exportExcel (exportExcel.js:141:12)
    at TableRenderer.<anonymous> (index.js:1275:54)
    at step (tslib.es6.js:147:23)
    at Object.next (tslib.es6.js:128:53)
    at tslib.es6.js:121:71
    at new Promise (<anonymous>)
    at __awaiter (tslib.es6.js:117:12)
    at index.js:1269:68
crud.js:469 Uncaught (in promise) TypeError: papaparse.unparse is not a function

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
    "amis": "^3.3.0",
    "amis-core": "^3.3.0",
    "amis-formula": "^3.3.0",
    "amis-ui": "^3.3.0",
3. 粘贴有问题的完整 `amis schema` 代码：
"headerToolbar": [
    "reload",
    "export-csv"
]

4. 操作步骤
直接添加在头部export-csv

**Comment by wnki** [comment]
打包后可以使用但是在本地启动服务不可使用

**Comment by zybzzc** [comment]
首先排除排除 vite 的锅
