### ISSUE TITLE
编辑器中  jsonview 或  表单 开启debug 时 直接渲染失败

### ISSUE THREAD

**Issue by hyzx86** [baidu/amis#8295]
#### 描述问题：
 编辑器中 表单 开启debug 直接渲染失败
 Error: Element type is invalid. Received a promise that resolves to: [object Module]. Lazy element type must resolve to

#### 截图或视频：
最新版本 ：
 
![image](https://github.com/baidu/amis/assets/15613121/6600eaf5-5798-443d-89c2-3c46dce8eda1)

可以的话，尽可能提供截图或视频来补充描述你的问题...

#### 如何复现（请务必完整填写下面内容）：
拖拽一个表单，然后直接开启 debug
1. 你是如何使用 amis 的？
vite + react + pnpm

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
    "amis": "^3.4.2",
    "amis-core": "3.4.2",
    "amis-editor": "5.6.1",
    "amis-editor-core": "5.6.1",
    "amis-formula": "3.4.2",
    "amis-ui": "^3.4.2",
3. 粘贴有问题的完整 `amis schema` 代码：
```json
{
  "type": "form",
  "id": "u:891814ab0881",
  "title": "表单",
  "mode": "horizontal",
  "dsType": "api",
  "feat": "Insert",
  "body": [
  ],
  "actions": [
    {
      "type": "button",
      "label": "提交",
      "onEvent": {
        "click": {
          "actions": [
            {
              "actionType": "submit",
              "componentId": "u:891814ab0881"
            }
          ]
        }
      },
      "level": "primary",
      "id": "u:9c5fed5bee54"
    }
  ],
  "resetAfterSubmit": true,
  "debug": true
}
```

会是我环境问题吗？

vite.config.ts
```ts
const { resolve } = require('path');
import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import monacoEditorPlugin from 'vite-plugin-monaco-editor';
import svgr from 'vite-plugin-svgr';
// https://vitejs.dev/config/
export default defineConfig({
  server: {
    port: 2688,
    host: '0.0.0.0'
  },
  resolve: {
    alias: {
      '@': resolve(__dirname, './src')
    }
  },
  plugins: [ 
    react({
      babel: {
        parserOpts: {
          plugins: [
            'decorators-legacy', 'classProperties'
          ]
        }
      }
    }),
    svgr({
      exportAsDefault: true,
      svgrOptions: {
        svgProps: {
          className: 'icon'
        },
        prettier: false,
        dimensions: false
      }
    }),
    monacoEditorPlugin({}),
  ],
  build: {
    manifest: true,
    rollupOptions: {
      input: {
        main: resolve(__dirname, 'index.html'),
      }
    }
  }
});

```

package.json

```json
{
  "dependencies": {
    "@ant-design/icons": "^5.2.6",
    "@ant-design/pro-components": "^2.6.23",
    "@ant-design/use-emotion-css": "^1.0.4",
    "@antv/x6": "^2.11.5",
    "@antv/x6-plugin-clipboard": "^2.1.6",
    "@antv/x6-plugin-history": "^2.2.3",
    "@antv/x6-plugin-keyboard": "^2.2.1",
    "@antv/x6-plugin-minimap": "^2.0.5",
    "@antv/x6-plugin-scroller": "^2.0.10",
    "@antv/x6-plugin-selection": "^2.1.7",
    "@antv/x6-plugin-snapline": "^2.1.7",
    "@antv/x6-plugin-transform": "^2.1.7",
    "@antv/x6-react-shape": "^2.2.2",
    "@antv/xflow": "^1.0.55",
    "@antv/xflow-hook": "^1.0.55",
    "@apollo/client": "^3.8.4",
    "@emotion/css": "^11.11.2",
    "@fortawesome/fontawesome-free": "^6.4.2",
    "@types/jest": "^27.5.2",
    "ahooks": "^3.7.8",
    "amis": "^3.4.2",
    "amis-core": "3.4.2",
    "amis-editor": "5.6.1",
    "amis-editor-core": "5.6.1",
    "amis-formula": "3.4.2",
    "amis-ui": "^3.4.2",
    "antd": "^5.9.4",
    "apollo-client": "^2.6.10",
    "axios": "^0.26.1",
    "bootstrap": "3.4.1",
    "classnames": "^2.3.2",
    "copy-to-clipboard": "^3.3.3",
    "core-js": "^3.32.2",
    "dayjs": "^1.11.10",
    "i18n-runtime": "0.0.23-beta.8",
    "lodash": "^4.17.21",
    "mobx": "^4.5.0",
    "mobx-react": "^6.3.1",
    "mobx-state-tree": "^3.17.3",
    "monaco-editor": "^0.36.1",
    "oidc-client-ts": "^2.2.5",
    "path-to-regexp": "^6.2.1",
    "pinyin-pro": "^3.16.7",
    "query-string": "^8.1.0",
    "rc-menu": "^9.12.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-full-screen": "^1.1.1",
    "react-hook-form": "^7.46.2",
    "react-monaco-editor": "^0.54.0",
    "react-router": "5.2.1",
    "react-router-dom": "5.3.0",
    "strip-json-comments": "^5.0.1",
    "tslib": "^2.6.2"
  },
  "devDependencies": {
    "@babel/core": "^7.22.20",
    "@babel/generator": "^7.22.9",
    "@babel/parser": "^7.22.7",
    "@babel/traverse": "^7.22.8",
    "@babel/types": "^7.22.5",
    "@rollup/plugin-replace": "^5.0.1",
    "@types/lodash": "^4.14.199",
    "@types/node": "^11.15.54",
    "@types/qs": "^6.9.8",
    "@types/react": "^18.0.24",
    "@types/react-dom": "^18.0.8",
    "@types/react-router": "^5.1.20",
    "@types/react-router-dom": "^5.3.3",
    "@vitejs/plugin-react": "^2.2.0",
    "@vue/compiler-sfc": "^3.3.4",
    "axios-mock-adapter": "^1.22.0",
    "cross-env": "^7.0.3",
    "css-loader": "^6.8.1",
    "eslint": "^8.50.0",
    "eslint-plugin-import": "^2.28.1",
    "eslint-plugin-react": "^7.33.2",
    "express": "^4.18.2",
    "file-loader": "^6.2.0",
    "less": "^4.2.0",
    "less-loader": "^11.1.3",
    "plugin-react-i18n": "1.0.1",
    "postcss-scss": "^4.0.6",
    "prettier": "^2.8.8",
    "prismjs": "^1.29.0",
    "rollup-pluginutils": "^2.8.2",
    "setprototypeof": "^1.2.0",
    "style-loader": "^3.3.3",
    "ts-loader": "^9.4.4",
    "typescript": "^4.9.5",
    "url-loader": "^4.1.1",
    "vite": "^4.4.9",
    "vite-plugin-monaco-editor": "^1.1.0",
    "vite-plugin-svgr": "^2.2.2"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }}

```

**Comment by hyzx86** [comment]
React will try to recreate this component tree from scratch using the error boundary you provided, Scoped(WithStore(FormRenderer2)).

完整错误信息
```
react-dom.development.js:20013  Uncaught Error: Element type is invalid. Received a promise that resolves to: [object Module]. Lazy element type must resolve to a class or function.
    at mountLazyComponent (react-dom.development.js:20013:9)
    at beginWork (react-dom.development.js:21593:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at performConcurrentWorkOnRoot (react-dom.development.js:25738:74)
mountLazyComponent @ react-dom.development.js:20013
beginWork @ react-dom.development.js:21593
callCallback2 @ react-dom.development.js:4164
invokeGuardedCallbackDev @ react-dom.development.js:4213
invokeGuardedCallback @ react-dom.development.js:4277
beginWork$1 @ react-dom.development.js:27451
performUnitOfWork @ react-dom.development.js:26557
workLoopSync @ react-dom.development.js:26466
renderRootSync @ react-dom.development.js:26434
performConcurrentWorkOnRoot @ react-dom.development.js:25738
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 13 more frames

显示简略信息
react-dom.development.js:20013  Uncaught Error: Element type is invalid. Received a promise that resolves to: [object Module]. Lazy element type must resolve to a class or function.

    at mountLazyComponent (react-dom.development.js:20013:9)
    at beginWork (react-dom.development.js:21593:16)
    at HTMLUnknownElement.callCallback2 (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27451:7)
    at performUnitOfWork (react-dom.development.js:26557:12)
    at workLoopSync (react-dom.development.js:26466:5)
    at renderRootSync (react-dom.development.js:26434:7)
    at recoverFromConcurrentError (react-dom.development.js:25850:20)




the above error occurred in one of your React components:

    at Suspense
    at div
    at JSONFieldRenderer (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-BVXK5DTV.js?v=678368aa:39753:38)
    at SchemaRenderer2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:31931:26)
    at t (http://salesportal.localhost:2688/node_modules/.vite/deps/amis-editor.js?v=678368aa:16326:28)
    at form
    at div
    at div
    at PanelRenderer (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-BVXK5DTV.js?v=678368aa:38247:38)
    at SchemaRenderer2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:31931:26)
    at FormRenderer2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:26359:26)
    at StoreFactory2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:24446:30)
    at ScopedComponent2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:24309:28)
    at t (http://salesportal.localhost:2688/node_modules/.vite/deps/amis-editor.js?v=678368aa:16300:28)
    at t (http://salesportal.localhost:2688/node_modules/.vite/deps/amis-editor.js?v=678368aa:16355:28)
    at i (http://salesportal.localhost:2688/node_modules/.vite/deps/amis-editor.js?v=678368aa:17570:23)
    at SchemaRenderer2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:31931:26)
    at t (http://salesportal.localhost:2688/node_modules/.vite/deps/amis-editor.js?v=678368aa:16326:28)
    at div
    at div
    at div
    at div
    at PageRenderer (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-BVXK5DTV.js?v=678368aa:37930:24)
    at StoreFactory2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:24446:30)
    at ScopedComponent2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:24309:28)
    at t (http://salesportal.localhost:2688/node_modules/.vite/deps/amis-editor.js?v=678368aa:16300:28)
    at t (http://salesportal.localhost:2688/node_modules/.vite/deps/amis-editor.js?v=678368aa:16355:28)
    at i (http://salesportal.localhost:2688/node_modules/.vite/deps/amis-editor.js?v=678368aa:17570:23)
    at SchemaRenderer2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:31931:26)
    at RootRenderer2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:31599:22)
    at ImageGallery2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-EOG53SGU.js?v=678368aa:40899:45)
    at class_1 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:30613:26)
    at class_1 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:27912:26)
    at Root2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:32301:40)
    at ScopedComponent2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:24309:28)
    at class_1 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:32259:26)
    at AMISRenderer (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-PZPECKHG.js?v=678368aa:32442:20)
    at div
    at t (http://salesportal.localhost:2688/node_modules/.vite/deps/amis-editor.js?v=678368aa:14331:30)
    at div
    at div
    at div
    at t (http://salesportal.localhost:2688/node_modules/.vite/deps/amis-editor.js?v=678368aa:14162:30)
    at div
    at div
    at div
    at t (http://salesportal.localhost:2688/node_modules/.vite/deps/amis-editor.js?v=678368aa:18048:12)
    at div
    at div
    at wrappedComponent (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-Z5VVTM3J.js?v=678368aa:303:12)
    at http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-Z5VVTM3J.js?v=678368aa:800:41
    at Route2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-VXLTSU7W.js?v=678368aa:1593:29)
    at Switch2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-VXLTSU7W.js?v=678368aa:1737:29)
    at Suspense
    at wrappedComponent (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-Z5VVTM3J.js?v=678368aa:303:12)
    at http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-Z5VVTM3J.js?v=678368aa:800:41
    at main
    at http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-JRZQLFYL.js?v=678368aa:20161:20
    at Content
    at ErrorBoundary2 (http://salesportal.localhost:2688/node_modules/.vite/deps/@ant-design_pro-components.js?v=678368aa:7977:5)
    at WrapContent2 (http://salesportal.localhost:2688/node_modules/.vite/deps/@ant-design_pro-components.js?v=678368aa:31206:52)
    at div
    at div
    at http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-JRZQLFYL.js?v=678368aa:20180:20
    at Layout
    at div
    at BaseProLayout2 (http://salesportal.localhost:2688/node_modules/.vite/deps/@ant-design_pro-components.js?v=678368aa:31331:13)
    at MotionWrapper (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-GWL2T5ZD.js?v=678368aa:3455:5)
    at ProviderChildren (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-GWL2T5ZD.js?v=678368aa:3605:9)
    at ConfigProvider (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-GWL2T5ZD.js?v=678368aa:3843:31)
    at SWRConfig (http://salesportal.localhost:2688/node_modules/.vite/deps/@ant-design_pro-components.js?v=678368aa:4514:11)
    at ConfigProviderContainer2 (http://salesportal.localhost:2688/node_modules/.vite/deps/@ant-design_pro-components.js?v=678368aa:7758:24)
    at LocaleProvider (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-GWL2T5ZD.js?v=678368aa:2036:17)
    at MotionWrapper (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-GWL2T5ZD.js?v=678368aa:3455:5)
    at ProviderChildren (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-GWL2T5ZD.js?v=678368aa:3605:9)
    at ConfigProvider (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-GWL2T5ZD.js?v=678368aa:3843:31)
    at ProConfigProvider2 (http://salesportal.localhost:2688/node_modules/.vite/deps/@ant-design_pro-components.js?v=678368aa:7847:24)
    at MotionWrapper (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-GWL2T5ZD.js?v=678368aa:3455:5)
    at ProviderChildren (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-GWL2T5ZD.js?v=678368aa:3605:9)
    at ConfigProvider (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-GWL2T5ZD.js?v=678368aa:3843:31)
    at ProLayout2 (http://salesportal.localhost:2688/node_modules/.vite/deps/@ant-design_pro-components.js?v=678368aa:31593:28)
    at div
    at wrappedComponent (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-Z5VVTM3J.js?v=678368aa:303:12)
    at http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-Z5VVTM3J.js?v=678368aa:800:41
    at wrappedComponent (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-Z5VVTM3J.js?v=678368aa:303:12)
    at http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-Z5VVTM3J.js?v=678368aa:800:41
    at Route2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-VXLTSU7W.js?v=678368aa:1593:29)
    at Switch2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-VXLTSU7W.js?v=678368aa:1737:29)
    at div
    at Suspense
    at Router2 (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-VXLTSU7W.js?v=678368aa:1313:30)
    at BrowserRouter2 (http://salesportal.localhost:2688/node_modules/.vite/deps/react-router-dom.js?v=678368aa:54:35)
    at wrappedComponent (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-Z5VVTM3J.js?v=678368aa:303:12)
    at Provider (http://salesportal.localhost:2688/node_modules/.vite/deps/chunk-Z5VVTM3J.js?v=678368aa:782:24)
    at http://salesportal.localhost:2688/src/App.tsx?t=1696664079122:16:3

React will try to recreate this component tree from scratch using the error boundary you provided, Scoped(WithStore(FormRenderer2)).
overrideMethod @ console.js:213
logCapturedError @ react-dom.development.js:18687
callback @ react-dom.development.js:18755
callCallback @ react-dom.development.js:13923
commitUpdateQueue @ react-dom.development.js:13944
commitLayoutEffectOnFiber @ react-dom.development.js:23364
commitLayoutMountEffects_complete @ react-dom.development.js:24688
commitLayoutEffects_begin @ react-dom.development.js:24674
commitLayoutEffects_begin @ react-dom.development.js:24656
commitLayoutEffects_begin @ react-dom.development.js:24656
commitLayoutEffects @ react-dom.development.js:24612
commitRootImpl @ react-dom.development.js:26823
commitRoot @ react-dom.development.js:26682
finishConcurrentRender @ react-dom.development.js:25892
performConcurrentWorkOnRoot @ react-dom.development.js:25809
workLoop @ scheduler.development.js:266
flushWork @ scheduler.development.js:239
performWorkUntilDeadline @ scheduler.development.js:533
Show 18 more frames
显示简略信息
```

**Comment by hyzx86** [comment]
发现是 jsonview 这个东西懒加载的问题， 使用这个方法可以解决,


//修复jsonview 等懒加载无法正常加载的问题
import 'react-json-view';

**Comment by hyzx86** [comment]
pnpm i react-json-view 似乎同样能解决

**Comment by SuCicada** [comment]
too awesome, thank you
