### ISSUE TITLE
最新代码，进入“主题编辑器”页面时报错

### ISSUE THREAD

**Issue by citynook** [baidu/amis#8922]
#### 描述问题：
下载 2023.11.28 日最新代码，进入“主题编辑器”页面时报错

#### 截图或视频：
![image](https://github.com/baidu/amis/assets/127393297/c98feba2-fb73-4239-821a-5575ba377633)

TypeError: value2.replace is not a function

    at _a (http://127.0.0.1:8888/packages/amis-core/src/renderers/wrapControl.tsx:22:7)
    at _a (http://127.0.0.1:8888/packages/amis-core/src/WithRootStore.tsx:10:7)
    at SchemaRenderer (http://127.0.0.1:8888/packages/amis-core/src/SchemaRenderer.tsx:35:5)
    at div
    at Transition2 (http://127.0.0.1:8888/node_modules/.vite/deps/react-transition-group_Transition.js?v=83b4eb5d:65:30)
    at TabComponent (http://127.0.0.1:8888/packages/amis-ui/src/components/Tabs.tsx:49:5)
    at _a (http://127.0.0.1:8888/packages/amis-core/src/theme.tsx:70:7)
    at div
    at div
    at Tabs (http://127.0.0.1:8888/packages/amis-ui/src/components/Tabs.tsx:142:5)
    at UncontrolledComponent2 (http://127.0.0.1:8888/node_modules/.vite/deps/chunk-THWDX4UC.js?v=83b4eb5d:243:37)
    at _a (http://127.0.0.1:8888/packages/amis-core/src/theme.tsx:70:7)
    at _a (http://127.0.0.1:8888/packages/amis-core/src/locale.tsx:75:7)
    at TabsRenderer (http://127.0.0.1:8888/packages/amis/src/renderers/Tabs.tsx:543:5)
    at SchemaRenderer (http://127.0.0.1:8888/packages/amis-core/src/SchemaRenderer.tsx:35:5)
    at div
    at div
    at GridRenderer (http://127.0.0.1:8888/packages/amis/src/renderers/Grid.tsx:132:27)
    at SchemaRenderer (http://127.0.0.1:8888/packages/amis-core/src/SchemaRenderer.tsx:35:5)
    at form
    at div
    at div
    at PanelRenderer (http://127.0.0.1:8888/packages/amis/src/renderers/Panel.tsx:164:28)
    at SchemaRenderer (http://127.0.0.1:8888/packages/amis-core/src/SchemaRenderer.tsx:35:5)
    at FormRenderer (http://127.0.0.1:8888/packages/amis-core/src/renderers/Form.tsx:1109:5)
    at StoreFactory (http://127.0.0.1:8888/packages/amis-core/src/WithStore.tsx:41:9)
    at ScopedComponent (http://127.0.0.1:8888/packages/amis-core/src/Scoped.tsx:276:7)
    at SchemaRenderer (http://127.0.0.1:8888/packages/amis-core/src/SchemaRenderer.tsx:35:5)
    at RootRenderer (http://127.0.0.1:8888/packages/amis-core/src/RootRenderer.tsx:29:5)
    at _ImageGallery (http://127.0.0.1:8888/packages/amis-ui/src/components/ImageGallery.tsx:46:5)
    at _a (http://127.0.0.1:8888/packages/amis-core/src/locale.tsx:75:7)
    at _a (http://127.0.0.1:8888/packages/amis-core/src/theme.tsx:70:7)
    at Root (http://127.0.0.1:8888/packages/amis-core/src/Root.tsx:42:8)
    at ScopedComponent (http://127.0.0.1:8888/packages/amis-core/src/Scoped.tsx:276:7)
    at _a (http://127.0.0.1:8888/packages/amis-core/src/StatusScoped.tsx:25:7)
    at AMISRenderer (http://127.0.0.1:8888/packages/amis-core/src/index.tsx:133:3)
    at div
    at SchemaRenderer (http://127.0.0.1:8888/examples/components/SchemaRender.jsx:42:7)
    at C2 (http://127.0.0.1:8888/node_modules/.vite/deps/chunk-5NVFARTI.js?v=83b4eb5d:1104:37)
    at Route2 (http://127.0.0.1:8888/node_modules/.vite/deps/chunk-5NVFARTI.js?v=83b4eb5d:921:29)
    at Switch2 (http://127.0.0.1:8888/node_modules/.vite/deps/chunk-5NVFARTI.js?v=83b4eb5d:1065:29)
    at Example (http://127.0.0.1:8888/examples/components/Example.jsx:817:16)
    at Route2 (http://127.0.0.1:8888/node_modules/.vite/deps/chunk-5NVFARTI.js?v=83b4eb5d:921:29)
    at Switch2 (http://127.0.0.1:8888/node_modules/.vite/deps/chunk-5NVFARTI.js?v=83b4eb5d:1065:29)
    at Suspense
    at div
    at div
    at div
    at div
    at Layout (http://127.0.0.1:8888/packages/amis-ui/src/components/Layout.tsx:20:3)
    at _a (http://127.0.0.1:8888/packages/amis-core/src/theme.tsx:70:7)
    at App (http://127.0.0.1:8888/examples/components/App.tsx:112:5)
    at C2 (http://127.0.0.1:8888/node_modules/.vite/deps/chunk-5NVFARTI.js?v=83b4eb5d:1104:37)
    at Route2 (http://127.0.0.1:8888/node_modules/.vite/deps/chunk-5NVFARTI.js?v=83b4eb5d:921:29)
    at Switch2 (http://127.0.0.1:8888/node_modules/.vite/deps/chunk-5NVFARTI.js?v=83b4eb5d:1065:29)
    at Router2 (http://127.0.0.1:8888/node_modules/.vite/deps/chunk-5NVFARTI.js?v=83b4eb5d:644:30)
    at BrowserRouter2 (http://127.0.0.1:8888/node_modules/.vite/deps/react-router-dom.js?v=83b4eb5d:56:35)
    at entry
    at AppWithCallbackAfterRender (http://127.0.0.1:8888/examples/index.jsx:23:3)

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`、`npm` 或`其他`...

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在

3. 粘贴有问题的完整 `amis schema` 代码：
```
code here...
```

4. 操作步骤
请简单描述一下复现的操作步骤...

**Comment by nwind** [comment]
未复现，删了 node_modules 重新安装试试，另外可以点一下那个红点看究竟是哪一行报错
<img width="36" alt="image" src="https://github.com/baidu/amis/assets/6889/f4b50bdd-fbb0-431f-9193-fed5ac024544">

**Comment by citynook** [comment]
@nwind 我是下载最新代码然后安装的依赖~请看下是不是要的下面的debug信息
![image](https://github.com/baidu/amis/assets/127393297/7855ed97-3415-439e-bdeb-6d916726e0fa)
![image](https://github.com/baidu/amis/assets/127393297/ed722cf3-9b93-41d6-8083-d6c93e032b09)

**Comment by citynook** [comment]
我在几天前曾经下载过当时的版本，在主题编辑器中改了一些设定，今天下载新版本后进入主题编辑器就报错，刚才把浏览器缓存清了，就一切正常了，不清楚哪些缓存数据造成新版本无法兼容。

**Comment by citynook** [comment]
先关闭，不是啥大问题
