### ISSUE TITLE
amis导出Excel报错 amis.define is not a function  at exceljs.js:2:6

### ISSUE THREAD

**Issue by fanfan6** [baidu/amis#9718]
#### 描述问题：

请用一段清晰简洁的文字描述问题是什么...
在用SDK方式中，"headerToolbar": [{"type": "export-excel", "label": "导出Excel"}] 方式导出Excel时，报错amis.define is not a function  at exceljs.js:2:6

#### 截图或视频：

可以的话，尽可能提供截图或视频来补充描述你的问题...
<img width="1074" alt="Snipaste_2024-03-04_16-08-09" src="https://github.com/baidu/amis/assets/22702343/2bf587f6-04f7-4cdd-9bf5-ab022fe4614a">

#### 如何复现（请务必完整填写下面内容）：

1. 你是如何使用 amis 的？
`sdk`

2. amis 版本是什么？请先在最新 beta 版本测试问题是否存在
6.2.2

3. 粘贴有问题的完整 `amis schema` 代码：
```
{
    "type": "crud",
    "syncLocation": "false",
    "api": "http://localhost:8000/bill/api/pay/list",
    "perPage": 50,
    "autoFillHeight": "true",
    "headerToolbar": [{"type": "export-excel", "label": "导出Excel", "columns": ["appid", "bill_date", "query_cnt", "hit_cnt", "bill_amount"]}],
    "footerToolbar": ["statistics", {"type": "pagination", "layout": "perPage,pager,go"}],
    "filter": {
        "body": [
            {"label": "选项", "type": "select", "name": "appid", "clearable": "true", "source": "/bill/api/pay/appid_list"},
            {"label": "选项", "type": "select", "name": "service", "clearable": "true", "source": "/bill/api/pay/service_list?appid=${appid}"},
            {"type": "input-date-range", "name": "start", "extraName": "end", "clearable": "true", "label": "日期范围"},
        ],
        "actions": [{"type": "submit", "level": "primary", "label": "查询"}],
    },
    "columns": [
        {"name": "appid", "label": "商户", "fixed": "left"},
        {"name": "service", "label": "服务", "fixed": "left"},
        {"name": "bill_date", "label": "日期"},
        {"name": "query_cnt", "label": "查询数量"},
        {"name": "hit_cnt", "label": "计费数量"},
        {"name": "bill_amount", "label": "金额"},
    ],
}
```

4. 操作步骤
    "headerToolbar": [{"type": "export-excel", "label": "导出Excel", "columns": ["appid", "bill_date", "query_cnt", "hit_cnt", "bill_amount"]}],

**Comment by 2betop** [comment]
不能复现，amis.define 是在 sdk.js 里面定义的
